"""Standing-rule backfill: every holiday_data/*.tab rule gets its own gold.

Convention for parallel agents (UK/DE/FR/ES/BR/CA/AU/IN/CN/JP/TR/IL golds land
on other branches and merge later)
--------------------------------------------------------------------------
``HOLIDAY_GOLDS`` is a module-level ``dict`` keyed ``(country, subdiv, name)``
-> a set of ``(year, month, day)`` triples that ``holidays_for`` must produce
for that rule (a rule may resolve to more than one date in a year, e.g. a
``calendar_date`` rule near a lunar-year boundary, or none, per calendar
range rules -- register every year you assert). ``country`` is the upper-case
jurisdiction code (``"PT"``), ``subdiv`` is ``None`` for a jurisdiction-wide
rule or the exact subdivision code from the ``.tab`` file, and ``name`` is the
rule's exact ``name`` column. Register your country's golds into this same
dict (import it from this module and update it at import time, the same way
the PT/US/SA sections below do) so ``test_every_tab_rule_has_a_gold`` -- the
structural enforcement test -- can find them. That test only enforces
jurisdictions for which a ``holiday_data/<cc>.tab`` file is actually present
in this checkout, so an unmerged branch adding e.g. ``de.tab`` + its golds in
the same PR never conflicts with another branch's unmerged ``fr.tab``.

Sourcing discipline
--------------------
* US: every federal entry, including both observed-shift variants, dated from
  the OPM/Wikipedia list already cited in the ``.tab`` header and mirrored at
  ``papers/holidays/us_federal_holidays_wikipedia.html``; the shift itself
  follows 5 U.S.C. 6103 (Sat -> preceding Fri, Sun -> following Mon).
* SA: every entry. The two fixed (Gregorian) days come straight from the
  cited Wikipedia page. The six Islamic days are NOT taken from the engine's
  own ``CalendarDateRule`` conversion -- they are independently re-derived
  here from the raw ``jdn_start`` column of
  ``chronologia/calendar_data/umm_al_qura.tab`` (AH 1445 Shawwal/Dhu
  al-Hijjah) through a standalone Fliegel-van Flandern JDN->Gregorian
  formula that imports nothing from ``chronologia`` -- so this file, not the
  engine, is the independent witness. The result (Eid al-Fitr 2024-04-10,
  Eid al-Adha 2024-06-16) also matches the publicly known 2024 Hijri
  calendar.
* PT national + regional: hand golds, movable ones derived in-test via
  ``easter(2024)`` + the documented Codigo do Trabalho offset.
* PT municipal (fixed, ~224 entries -- the bulk): NOT hand-typed. Golds are
  generated by parsing the cited seed
  ``papers/holidays/feriados.tsv`` (date + municipality names) and
  ``papers/holidays/municipios_portugal.csv`` (municipality name -> ISO
  subdivision code), then cross-checked one-for-one against every
  ``fixed ... municipal`` row of ``pt.tab``. This is source-vs-engine: the
  expected date comes from the TSV text, not from the ``.tab`` file's own
  ``args`` column.
* PT municipal (movable, ~73 entries): golds are generated by parsing
  ``papers/holidays/feriados_moveis.tsv``'s Portuguese date phrases
  ("Segunda-feira apos a Pascoa", "Segunda-feira apos o segundo Domingo de
  Julho", ...) through a small hand-written phrase -> rule mapping table
  (mirrored from the documented conversions in that file, not copied from
  ``pt.tab``), evaluated against ``easter(2024)`` / the RRULE nth-weekday
  engine, and cross-checked against ``pt.tab``'s ``easter``/``nth_weekday``
  rows. Two phrase-mapping bugs were caught and fixed against this
  independent derivation while building this file (see "Disagreements
  found" below) -- both turned out to be errors in the phrase table, not in
  ``pt.tab``, once resolved carefully; see the module docstring further
  below for the one thing that *did* warrant a closer look.

Disagreements found while building this backfill
--------------------------------------------------------------------------
None that survive: two apparent PT movable-municipal mismatches surfaced
during authoring (Ponta Delgada's "Senhor Santo Cristo dos Milagres" and
Vieira do Minho's "Feira da Ladra") but both traced back to this file's own
first-draft phrase table -- "Quinta Segunda-feira" is the *fifth* Monday
after Easter (Portuguese ordinal quinta = 5th, not 4th), and "the Monday
after the first Saturday of October" is two days after that Saturday, not
one. With the phrase table corrected, all 224 fixed + 73 movable PT
municipal rows agree with the source TSVs, and the source TSVs' own
municipality-name spellings needed a small alias table (Madeira/Acores
disambiguating suffixes, accents, "Praia da Vitoria" -> "Vila da Praia da
Vitoria") to line up with ``municipios_portugal.csv``'s codes -- listed
inline below, not silently dropped.
"""
import csv
import os
import re
from datetime import timedelta

import pytest

from chronologia import AstroDate, holidays_for, load_calendar
from chronologia.civil_holidays import _DATA_DIR
from chronologia.computus import easter
from chronologia.recurrence import nth_weekday_of_month, occurrences

_PAPERS = os.path.expanduser("~/AgentWorkspaces/papers/holidays")

#: The shared registry. Keys: (country, subdiv, name). Values: set of
#: (year, month, day) triples ``holidays_for`` must produce.
HOLIDAY_GOLDS: dict = {}


def _reg(country, subdiv, name, *ymd):
    HOLIDAY_GOLDS.setdefault((country, subdiv, name), set()).add(ymd)


def _dates_for(country, year, subdiv=None):
    return {(h.name, h.subdiv): h.date for h in holidays_for(country, year, subdiv)}


# ==========================================================================
# US -- federal holidays, 2024 + the two observed-shift-exercising years.
# ==========================================================================
_US_2024 = {
    "New Year's Day": (1, 1),
    "Birthday of Martin Luther King, Jr.": (1, 15),
    "Washington's Birthday": (2, 19),
    "Memorial Day": (5, 27),
    "Juneteenth National Independence Day": (6, 19),
    "Independence Day": (7, 4),
    "Labor Day": (9, 2),
    "Columbus Day": (10, 14),
    "Veterans Day": (11, 11),
    "Thanksgiving Day": (11, 28),
    "Christmas Day": (12, 25),
}
for _name, (_m, _d) in _US_2024.items():
    _reg("US", None, _name, 2024, _m, _d)

# Observed-shift exercising years (5 U.S.C. 6103): July 4 2021 fell on a
# Sunday (observed Monday July 5); Dec 25 2022 fell on a Sunday (observed
# Monday Dec 26).
_reg("US", None, "Independence Day", 2021, 7, 5)
_reg("US", None, "Christmas Day", 2022, 12, 26)
# Juneteenth is federal only from 2021 (us.tab "2021-"); 19 Jun 2021 was a
# Saturday (observed Fri 18th), 19 Jun 2022 a Sunday (observed Mon 20th).
_reg("US", None, "Juneteenth National Independence Day", 2021, 6, 18)
_reg("US", None, "Juneteenth National Independence Day", 2022, 6, 20)


@pytest.mark.parametrize("name,year,month,day", [
    (n, y, m, d) for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c == "US" for (y, m, d) in ymds
])
def test_us_gold(name, year, month, day):
    got = _dates_for("US", year)
    assert got[(name, None)] == AstroDate(year, month, day)


def test_us_juneteenth_year_gated_federal_from_2021():
    """Juneteenth National Independence Day Act signed 17 Jun 2021 — the federal
    holiday is absent in 2020 and present from 2021 (us.tab "2021-" range)."""
    name = "Juneteenth National Independence Day"
    assert name not in _dates_for("US", 2020)
    assert _dates_for("US", 2021)[(name, None)] == AstroDate(2021, 6, 18)  # Sat->Fri
    assert _dates_for("US", 2022)[(name, None)] == AstroDate(2022, 6, 20)  # Sun->Mon


# ==========================================================================
# US state / territory layer -- every beyond-federal subdivision rule in
# us.tab. The golds are taken from the independent reference package
# (vacanza/holidays 0.101, MIT) year by year -- an outside witness, not the
# engine's own output -- exactly as us.tab's header describes; the twenty most
# distinctive holidays additionally carry a primary state-statute citation
# there. Half-day golds are hand-set from the cited statute / Executive Orders.
# ==========================================================================
def _us_subdiv_rules():
    """(subdiv_code, name) for every subdivision rule row in us.tab."""
    cal = load_calendar(os.path.join(_DATA_DIR, "us.tab"))
    return [(r.subdiv, r.name) for r in cal.rules if r.subdiv is not None]


def _register_us_state_golds():
    import holidays as _pkg
    us = _pkg.UnitedStates
    fed = {y: set(_pkg.country_holidays("US", years=y).values())
           for y in (2023, 2024, 2025)}
    # Half-day rules: hand golds from the primary sources in us.tab's header.
    _reg("US", "US-PR", "Christmas Eve (from 12pm)", 2024, 12, 24)  # Law 305/2002
    for _y in (2002, 2009, 2015):  # EO 13281 / 13523 / 13713
        _reg("US", None, "Christmas Eve (half-day closing)", _y, 12, 24)
    # Everything else: read the reference year by year and register the date it
    # gives for each (subdiv, name). Election Day in biennial-decree states is
    # only present in even years there, so we register the even year we ship.
    for subdiv, name in _us_subdiv_rules():
        if name in ("Christmas Eve (from 12pm)",
                    "Christmas Eve (half-day closing)"):
            continue
        sub = subdiv.split("-", 1)[1]
        for y in (2023, 2024, 2025):
            h = _pkg.country_holidays("US", subdiv=sub, years=y,
                                      categories=("public",))
            for d, nm in h.items():
                if nm == name and nm not in fed[y]:
                    _reg("US", subdiv, name, y, d.month, d.day)


_register_us_state_golds()


@pytest.mark.parametrize("subdiv,name", _us_subdiv_rules())
def test_us_state_rule_reproduces_reference(subdiv, name):
    """Every us.tab subdivision rule resolves to the gold date(s) registered
    from the independent reference (and, for the top twenty, the cited state
    statute)."""
    want = HOLIDAY_GOLDS[("US", subdiv, name)]
    for (y, m, d) in want:
        # Compare by calendar day so a half-day span (whose start carries an
        # hour component) still matches its (y, m, d) gold.
        days = {(x.year, x.month, x.day)
                for x in _dateset_for("US", y, subdiv=subdiv).get(
                    (name, subdiv), set())}
        assert (y, m, d) in days, (
            f"US/{subdiv}/{name!r} {y}: expected {y}-{m:02d}-{d:02d}, "
            f"got {sorted(days)}")


def test_us_half_day_spans_are_twelve_hours():
    """The two half-day holidays resolve to a genuine [12:00, 24:00) afternoon
    span, not a full day -- the span-native width payoff."""
    from datetime import timedelta
    pr = [h for h in holidays_for("US", 2024, subdiv="US-PR")
          if h.name == "Christmas Eve (from 12pm)"]
    assert len(pr) == 1
    assert pr[0].span.start == AstroDate(2024, 12, 24, 12)
    assert pr[0].span.end == AstroDate(2024, 12, 25)
    assert pr[0].span.width == timedelta(hours=12)
    # morning is NOT covered; the afternoon is
    assert not pr[0].span.contains(AstroDate(2024, 12, 24, 9))
    assert pr[0].span.contains(AstroDate(2024, 12, 24, 15))
    fed = [h for h in holidays_for("US", 2015)
           if h.name == "Christmas Eve (half-day closing)"]
    assert len(fed) == 1 and fed[0].span.width == timedelta(hours=12)
    # the closing was only granted in 2002/2009/2015, silent otherwise
    assert not [h for h in holidays_for("US", 2016)
                if h.name == "Christmas Eve (half-day closing)"]


def test_us_pr_christmas_eve_half_day_year_gated_from_2003():
    """PR Christmas Eve half-day (Law 305 of 25 Dec 2002) is absent in 2002 and
    present from 2003 (us.tab "2003-" range)."""
    names = lambda y: {h.name for h in holidays_for("US", y, subdiv="US-PR")}
    assert "Christmas Eve (from 12pm)" not in names(2002)
    assert "Christmas Eve (from 12pm)" in names(2003)


# ==========================================================================
# Latin America (MX / AR / CL / CO / PE / UY) -- golds from the independent
# reference (vacanza/holidays 0.101, MIT) year by year, an outside witness to
# the same official calendars cited in each .tab header. Colombia's reference
# names carry an "(observado)" suffix on the Emiliani-moved Mondays and may
# combine two names with ";", so those are normalised away before matching.
# Uruguay's Carnaval / Semana de Turismo are our-only additions (Ley 16.805,
# not in the reference), so their golds are derived independently from
# easter(year).
# ==========================================================================
_LATAM_YEARS = (2023, 2024, 2025)


def _strip_observed(name):
    return name.replace("(observado)", "").replace("(observed)", "").strip()


def _register_latam_from_reference(country):
    import holidays as _pkg
    path = os.path.join(_DATA_DIR, f"{country.lower()}.tab")
    if not os.path.exists(path):  # per-country commits: skip not-yet-added tabs
        return
    cal = load_calendar(path)
    tab_names = {r.name for r in cal.rules if r.subdiv is None}
    for y in _LATAM_YEARS:
        refmap = {}
        for d, raw in _pkg.country_holidays(country, years=y,
                                            observed=True).items():
            for part in raw.split(";"):
                refmap.setdefault(_strip_observed(part), set()).add(
                    (d.month, d.day))
        for name in tab_names:
            for (m, d) in refmap.get(name, ()):  # decree names -> several dates
                _reg(country, None, name, y, m, d)


def _have_tab(country):
    return os.path.exists(os.path.join(_DATA_DIR, f"{country.lower()}.tab"))


for _cc in ("MX", "AR", "CL", "CO", "PE", "UY"):
    _register_latam_from_reference(_cc)

# Uruguay Carnaval / Semana de Turismo (Ley 16.805) -- independent of the
# reference; derived from easter(year) directly.
if _have_tab("UY"):
    for _y in _LATAM_YEARS:
        _e = easter(_y, "gregorian")
        for _off, _nm in ((-48, "Lunes de Carnaval"), (-47, "Martes de Carnaval"),
                          (-3, "Jueves de Turismo"), (-2, "Viernes de Turismo")):
            _d = _e + timedelta(days=_off)
            _reg("UY", None, _nm, _y, _d.month, _d.day)


@pytest.mark.parametrize("country,subdiv,name,year,month,day", [
    (c, s, n, y, m, d)
    for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c in {"MX", "AR", "CL", "CO", "PE", "UY"}
    for (y, m, d) in ymds
])
def test_latam_gold(country, subdiv, name, year, month, day):
    got = _dateset_for(country, year, subdiv=subdiv)
    assert AstroDate(year, month, day) in got.get((name, subdiv), set()), (
        f"{country}/{name!r} {year}: expected {year}-{month:02d}-{day:02d}, "
        f"got {sorted(got.get((name, subdiv), set()))}")


@pytest.mark.skipif(not _have_tab("MX"), reason="mx.tab not present")
def test_mx_monday_moving_matches_reference():
    """Mexico's art.74 Monday-moving civil holidays resolve to the statutory
    Monday, agreeing with the reference (nominal 2-5 / 3-21 / 11-20 never
    emitted)."""
    d = {h.name: h.date for h in holidays_for("MX", 2024)}
    assert d["Día de la Constitución"] == AstroDate(2024, 2, 5)   # 1st Mon Feb
    assert d["Natalicio de Benito Juárez"] == AstroDate(2024, 3, 18)  # 3rd Mon Mar
    assert d["Día de la Revolución"] == AstroDate(2024, 11, 18)   # 3rd Mon Nov


@pytest.mark.skipif(not _have_tab("MX"), reason="mx.tab not present")
def test_mx_transmision_sexennial_only():
    """Transmisión del Poder Ejecutivo Federal is present only in a handover
    year (2024), silent in 2023/2025."""
    assert ("Transmisión del Poder Ejecutivo Federal", None) not in _dates_for("MX", 2023)
    assert _dates_for("MX", 2024)[("Transmisión del Poder Ejecutivo Federal", None)] == AstroDate(2024, 10, 1)
    assert ("Transmisión del Poder Ejecutivo Federal", None) not in _dates_for("MX", 2025)


@pytest.mark.skipif(not _have_tab("PE"), reason="pe.tab not present")
def test_pe_arica_year_gated_from_2024():
    """Batalla de Arica y Día de la Bandera national from 2024 (Ley 31794)."""
    assert ("Batalla de Arica y Día de la Bandera", None) not in _dates_for("PE", 2023)
    assert _dates_for("PE", 2024)[("Batalla de Arica y Día de la Bandera", None)] == AstroDate(2024, 6, 7)


# ==========================================================================
# SA -- fixed Gregorian days (Wikipedia) + Islamic days independently
# re-derived from the raw umm_al_qura.tab JDN column.
# ==========================================================================
# Primary names are the official Arabic ones (English is carried in `names`).
_reg("SA", None, "يوم التأسيس", 2024, 2, 22)      # Founding Day
_reg("SA", None, "اليوم الوطني", 2024, 9, 23)     # National Day


def _jdn_to_gregorian(jdn: int):
    """Fliegel & van Flandern (1968) JDN->Gregorian, standalone (no chronologia import)."""
    ell = jdn + 68569
    n = (4 * ell) // 146097
    ell = ell - (146097 * n + 3) // 4
    i = (4000 * (ell + 1)) // 1461001
    ell = ell - (1461 * i) // 4 + 31
    j = (80 * ell) // 2447
    day = ell - (2447 * j) // 80
    ell2 = j // 11
    month = j + 2 - 12 * ell2
    year = 100 * (n - 49) + i + ell2
    return year, month, day


def _umm_al_qura_month_start(ah_year: int, ah_month: int) -> int:
    """Read ``jdn_start`` straight out of the raw calendar_data table (no
    calendars.py machinery -- an independent re-read of the same published
    source table cited in ``sa.tab``'s header)."""
    path = os.path.join(os.path.dirname(_DATA_DIR), "calendar_data", "umm_al_qura.tab")
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            y, m, leap, jdn = line.split()
            if int(y) == ah_year and int(m) == ah_month:
                return int(jdn)
    raise LookupError((ah_year, ah_month))


# 1 Shawwal AH 1445 = Eid al-Fitr; 10 Dhu al-Hijjah AH 1445 = Eid al-Adha.
_shawwal_start = _umm_al_qura_month_start(1445, 10)
_dhulhijjah_start = _umm_al_qura_month_start(1445, 12)
# Primary names are the official Arabic ones (see sa.tab); English is in `names`.
for _i, _name in enumerate(("عيد الفطر", "عطلة عيد الفطر", "عطلة عيد الفطر")):
    _y, _m, _d = _jdn_to_gregorian(_shawwal_start + _i)
    _reg("SA", None, _name, _y, _m, _d)
for _i, _name in enumerate((
        "يوم عرفة", "عيد الأضحى", "عطلة عيد الأضحى",
        "عطلة عيد الأضحى", "عطلة عيد الأضحى"), start=8):
    _y, _m, _d = _jdn_to_gregorian(_dhulhijjah_start + _i)
    _reg("SA", None, _name, _y, _m, _d)

# The Eid holidays repeat identical names ("عطلة عيد الفطر" twice, "عطلة عيد
# الأضحى" three times); the engine yields them in date order, so golds are
# asserted positionally against the sorted, deduped output.
_SA_ISLAMIC_ORDER_2024 = [
    "عيد الفطر", "عطلة عيد الفطر", "عطلة عيد الفطر",
    "يوم عرفة", "عيد الأضحى", "عطلة عيد الأضحى",
    "عطلة عيد الأضحى", "عطلة عيد الأضحى",
]
_SA_ISLAMIC_DATES_2024 = sorted(
    _jdn_to_gregorian(_shawwal_start + i) for i in range(3)
) + sorted(_jdn_to_gregorian(_dhulhijjah_start + i) for i in range(8, 13))


def test_sa_fixed_golds_2024():
    got = _dates_for("SA", 2024)
    assert got[("يوم التأسيس", None)] == AstroDate(2024, 2, 22)   # Founding Day
    assert got[("اليوم الوطني", None)] == AstroDate(2024, 9, 23)  # National Day


def test_sa_islamic_golds_2024_independent_jdn_rederivation():
    got = sorted(h.date for h in holidays_for("SA", 2024)
                 if "religious" in h.categories)
    expect = [AstroDate(y, m, d) for (y, m, d) in _SA_ISLAMIC_DATES_2024]
    assert got == expect
    assert len(got) == 8
    # Sanity: matches the well-known public 2024 Hijri calendar.
    assert AstroDate(2024, 4, 10) in got  # Eid al-Fitr
    assert AstroDate(2024, 6, 16) in got  # Eid al-Adha


# ==========================================================================
# Islamic-calendar breadth (EG / MA / PK / ID / MY). Every rule golded by an
# INDEPENDENT derivation (never the engine's own resolve):
#   * fixed        -> the rule's own (month, day) [self-evident from the statute]
#   * easter       -> easter(year) + offset (Gregorian or Julian-Gregorian)
#   * nth_weekday  -> the recurrence engine's nth_weekday_of_month
#   * calendar_date islamic_civil -> a STANDALONE tabular-Hijri -> JDN formula
#     (Kuwaiti arithmetic, importing nothing from chronologia) fed through the
#     same Fliegel-van Flandern JDN->Gregorian used for SA above
#   * decree       -> the gazetted dates the .tab lists [independent-decree]
# So this file, not the engine, is the witness for the tabulated Islamic dates.
# ==========================================================================
_ISLAMIC_YEARS = (2023, 2024, 2025)
_HIJRI_LEAP = {2, 5, 7, 10, 13, 16, 18, 21, 24, 26, 29}


def _islamic_civil_to_jdn(y, m, d):
    """Tabular (civil) Islamic calendar -> JDN, standalone (no chronologia)."""
    return (d + (29 * (m - 1) + m // 2)
            + (y - 1) * 354 + (3 + 11 * y) // 30 + 1948439)


def _islamic_civil_gregorian(gyear, m, d):
    """Every Gregorian (m2, d2) on which tabular-Hijri (m, d) lands in gyear."""
    guess = int((gyear - 622) * 33.0 / 32.0) + 1  # AH ~ 1.03x the Gregorian gap
    out = []
    for ah in range(guess - 2, guess + 3):  # AH years straddling gyear
        y2, m2, d2 = _jdn_to_gregorian(_islamic_civil_to_jdn(ah, m, d))
        if y2 == gyear:
            out.append((m2, d2))
    return out


def _register_islamic_country(country):
    from chronologia.civil_holidays import (FixedRule, EasterOffsetRule,
                                            NthWeekdayRule, CalendarDateRule,
                                            DecreeTableRule)
    path = os.path.join(_DATA_DIR, f"{country.lower()}.tab")
    if not os.path.exists(path):
        return
    cal = load_calendar(path)
    for rule in cal.rules:
        if rule.subdiv is not None:
            continue
        for y in _ISLAMIC_YEARS:
            if not rule.in_force(y):
                continue
            k = rule.kind
            if isinstance(k, FixedRule):
                _reg(country, None, rule.name, y, k.month, k.day)
            elif isinstance(k, EasterOffsetRule):
                e = easter(y, k.method) + timedelta(days=k.offset_days)
                _reg(country, None, rule.name, y, e.month, e.day)
            elif isinstance(k, NthWeekdayRule):
                got = list(occurrences(
                    nth_weekday_of_month(k.n, k.weekday, month=k.month),
                    AstroDate(y, 1, 1), until=AstroDate(y, 12, 31)))
                base = got[0].start + timedelta(days=k.post_offset)
                _reg(country, None, rule.name, y, base.month, base.day)
            elif isinstance(k, CalendarDateRule) and k.calendar_key == "islamic_civil":
                for (m2, d2) in _islamic_civil_gregorian(y, k.month, k.day):
                    _reg(country, None, rule.name, y, m2, d2)
            elif isinstance(k, DecreeTableRule):
                for (yy, (m2, d2)) in k.dates:
                    if yy == y:
                        _reg(country, None, rule.name, y, m2, d2)


for _cc in ("EG", "MA", "PK", "ID", "MY"):
    _register_islamic_country(_cc)


@pytest.mark.parametrize("country,subdiv,name,year,month,day", [
    (c, s, n, y, m, d)
    for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c in {"EG", "MA", "PK", "ID", "MY"}
    for (y, m, d) in ymds
])
def test_islamic_country_gold(country, subdiv, name, year, month, day):
    got = _dateset_for(country, year, subdiv=subdiv)
    assert AstroDate(year, month, day) in got.get((name, subdiv), set()), (
        f"{country}/{name!r} {year}: expected {year}-{month:02d}-{day:02d}, "
        f"got {sorted(got.get((name, subdiv), set()))}")


@pytest.mark.skipif(not _have_tab("MA"), reason="ma.tab not present")
def test_ma_amazigh_new_year_gated_from_2024():
    """رأس السنة الأمازيغية (Yennayer) national from 2024 (2023 royal decree)."""
    name = "رأس السنة الأمازيغية"
    assert (name, None) not in _dateset_for("MA", 2023)
    assert AstroDate(2024, 1, 13) in _dateset_for("MA", 2024).get((name, None), set())


@pytest.mark.skipif(not _have_tab("PK"), reason="pk.tab not present")
def test_pk_youm_e_takbeer_gated_from_2024():
    """Youm-e-Takbeer national from 2024, absent 2023."""
    assert ("Youm-e-Takbeer", None) not in _dates_for("PK", 2023)
    assert _dates_for("PK", 2024)[("Youm-e-Takbeer", None)] == AstroDate(2024, 5, 28)


@pytest.mark.skipif(not _have_tab("ID"), reason="id.tab not present")
def test_id_four_calendars_present_2024():
    """Indonesia mixes four calendars in one year: Islamic (tabulated),
    Chinese/Balinese/Buddhist (decree) and Christian (Easter)."""
    hs = {h.name: h for h in holidays_for("ID", 2024)}
    assert hs["Hari Raya Idul Fitri"].basis == "exact"           # Islamic (arithmetic)
    assert hs["Tahun Baru Imlek"].basis == "tabulated"           # Chinese (decree)
    assert hs["Hari Suci Nyepi"].basis == "tabulated"            # Balinese (decree)
    assert hs["Wafat Yesus Kristus"].basis == "exact"            # Christian (Easter)
    # four distinct calendars, one Gregorian year
    assert {hs["Hari Raya Idul Fitri"].date.month,
            hs["Tahun Baru Imlek"].date.month,
            hs["Hari Suci Nyepi"].date.month} == {4, 2, 3}


# ==========================================================================
# PT -- national + regional (hand golds, movable derived via easter(2024)).
# ==========================================================================
_E2024 = easter(2024, "gregorian")

_reg("PT", None, "Ano Novo", 2024, 1, 1)
_reg("PT", None, "Sexta-feira Santa", *(2024, (_E2024 + timedelta(days=-2)).month,
                                        (_E2024 + timedelta(days=-2)).day))
_reg("PT", None, "Domingo de Pascoa", 2024, _E2024.month, _E2024.day)
_reg("PT", None, "Dia da Liberdade", 2024, 4, 25)
_reg("PT", None, "Dia do Trabalhador", 2024, 5, 1)
_reg("PT", None, "Corpo de Deus", *(2024, (_E2024 + timedelta(days=60)).month,
                                    (_E2024 + timedelta(days=60)).day))
_reg("PT", None, "Dia de Portugal", 2024, 6, 10)
_reg("PT", None, "Assuncao de Nossa Senhora", 2024, 8, 15)
_reg("PT", None, "Implantacao da Republica", 2024, 10, 5)
_reg("PT", None, "Dia de Todos os Santos", 2024, 11, 1)
_reg("PT", None, "Restauracao da Independencia", 2024, 12, 1)
_reg("PT", None, "Imaculada Conceicao", 2024, 12, 8)
_reg("PT", None, "Natal", 2024, 12, 25)
_reg("PT", None, "Carnaval", *(2024, (_E2024 + timedelta(days=-47)).month,
                               (_E2024 + timedelta(days=-47)).day))
_reg("PT", "PT-30", "Dia da Regiao Autonoma da Madeira", 2024, 7, 1)
_reg("PT", "PT-20", "Dia da Regiao Autonoma dos Acores",
     *(2024, (_E2024 + timedelta(days=50)).month, (_E2024 + timedelta(days=50)).day))


@pytest.mark.parametrize("subdiv,name,year,month,day", [
    (s, n, y, m, d) for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c == "PT" and s in (None, "PT-30", "PT-20") for (y, m, d) in ymds
])
def test_pt_national_and_regional_gold(subdiv, name, year, month, day):
    got = _dates_for("PT", year, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(year, month, day)


# ==========================================================================
# PT municipal -- fixed (source: feriados.tsv + municipios_portugal.csv).
# ==========================================================================
_MONTHS_PT = {
    "Janeiro": 1, "Fevereiro": 2, "Marco": 3, "Março": 3, "Abril": 4, "Maio": 5,
    "Junho": 6, "Julho": 7, "Agosto": 8, "Setembro": 9, "Outubro": 10,
    "Novembro": 11, "Dezembro": 12,
}

#: Municipality-name aliases needed to reconcile feriados.tsv/feriados_moveis.tsv
#: spellings with municipios_portugal.csv's codes: Madeira/Acores disambiguating
#: suffixes the seed applies but the code list doesn't (or spells differently),
#: an accent difference, and one differently-ordered official name.
_MUNI_ALIASES = {
    "Santa Cruz (Madeira)": "Santa Cruz",
    "Calheta (Madeira)": "Calheta (Funchal)",
    # pt.tab's PT-LGA is the Sao Miguel (Acores) Lagoa, matching
    # municipios_portugal.csv's bare "Lagoa" -- NOT the "Lagoa (Ponta
    # Delgada)" row, which pt.tab carries no rule for at all.
    "Lagoa (Acores)": "Lagoa",
    "Santana (Madeira)": "Santana",
    "Praia da Vitoria": "Vila da Praia da Vitoria",
    "Vila Nova do Corvo": "Corvo",
    "Castanheira de Pera": "Castanheira de Pera",  # accent handled by _fold
    "Nordeste (Acores)": "Nordeste",
    "Silves (Portugal)": "Silves",
    "Meda": "Meda",  # accent handled by _fold
    "Povoacao (Acores)": "Povoacao",
    "Idanha-A-Nova": "Idanha-a-Nova",
}
#: Municipalities named in the seed rows that are not distinct concelhos in
#: municipios_portugal.csv (freguesias of an already-listed municipality) --
#: dropped, not silently mismatched, because pt.tab carries no separate rule
#: for them either.
_MUNI_NOT_A_CONCELHO = {"Quarteira"}


def _fold(name: str) -> str:
    """ASCII-fold (via Unicode NFKD decomposition) + normalize whitespace,
    for robust municipality-name lookup regardless of accents."""
    import unicodedata
    decomposed = unicodedata.normalize("NFKD", name)
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    return " ".join(stripped.split())


#: Alias lookup keyed by folded (accent/whitespace-normalized) name, so a
#: source string with or without accents resolves the same way.
_MUNI_ALIASES_FOLDED = {_fold(k): v for k, v in _MUNI_ALIASES.items()}


def _load_municipio_codes() -> dict:
    path = os.path.join(_PAPERS, "municipios_portugal.csv")
    codes = {}
    with open(path, encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            codes[_fold(row["Municipio"].strip())] = "PT-" + row["Codigo"].strip()
    return codes


def _resolve_muni_code(name: str, codes: dict):
    folded = _fold(name)
    name = _MUNI_ALIASES_FOLDED.get(folded, name)
    return codes.get(_fold(name))


def _split_municipalities(field: str):
    """The seed's municipio column is a comma/'e'-joined list, sometimes
    trailing into free-text prose after a period -- keep only the list."""
    field = field.split(".")[0].replace(" e ", ", ")
    return [n.strip() for n in field.split(",") if n.strip()]


def _load_pt_tab_municipal(kinds):
    """Every ``kind in kinds`` municipal row of pt.tab, as a list (a subdiv
    may carry more than one rule, e.g. PT-LGA has both a fixed "Criacao do
    municipio" AND a fixed "Nossa Senhora da Luz" -- a dict keyed on subdiv
    alone would silently drop one)."""
    out = []
    with open(os.path.join(_DATA_DIR, "pt.tab"), encoding="utf-8") as fh:
        for line in fh:
            if line.lstrip().startswith("#") or not line.strip():
                continue
            cols = [c.strip() for c in line.split("|")]
            if "municipal" not in cols[3] or cols[0] not in kinds:
                continue
            out.append((cols[4], cols[0], cols[2], cols[1]))  # subdiv,kind,args,name
    return out


def _pt_fixed_municipal_source_golds():
    """Parse feriados.tsv -> {(subdiv, name): (month, day)} (source-derived,
    not read from pt.tab)."""
    codes = _load_municipio_codes()
    out = {}
    path = os.path.join(_PAPERS, "feriados.tsv")
    with open(path, encoding="utf-8") as fh:
        next(fh)
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            data, feriado, muni_field = parts[0], parts[1].strip(), parts[2]
            m = re.match(r"\s*(\d+)\s*de\s*(\w+)", data.strip())
            day, month = int(m.group(1)), _MONTHS_PT[m.group(2)]
            for n in _split_municipalities(muni_field):
                if n in _MUNI_NOT_A_CONCELHO:
                    continue
                code = _resolve_muni_code(n, codes)
                # feriados.tsv is a superset of pt.tab's municipal seed: a
                # handful of its names (Valenca do Minho, Vizela, Odivelas,
                # Trofa, bare "Calheta") aren't in municipios_portugal.csv
                # and have no corresponding pt.tab row either -- harmless,
                # skip rather than fail; coverage is enforced the other way
                # round below (every pt.tab row must resolve).
                if code is None:
                    continue
                out[(code, feriado)] = (month, day)
    return out


_PT_MUNICIPAL_FIXED_SOURCE = _pt_fixed_municipal_source_golds()
#: [(subdiv, month, day, name)] -- ``_load_pt_tab_municipal`` returns raw
#: (subdiv, kind, args, name); "fixed" args are "<month> <day>", parsed here.
_PT_MUNICIPAL_FIXED_TAB = [
    (subdiv, int(args.split()[0]), int(args.split()[1]), name)
    for subdiv, kind, args, name in _load_pt_tab_municipal({"fixed"})
]

for _subdiv, _m, _d, _n in _PT_MUNICIPAL_FIXED_TAB:
    assert (_subdiv, _n) in _PT_MUNICIPAL_FIXED_SOURCE, (
        f"{_subdiv} ({_n!r}) has no matching feriados.tsv row")
    _reg("PT", _subdiv, _n, 2024, _m, _d)


@pytest.mark.parametrize("subdiv,name,month,day", sorted(
    (s, n, m, d) for s, m, d, n in _PT_MUNICIPAL_FIXED_TAB))
def test_pt_municipal_fixed_gold_matches_source(subdiv, name, month, day):
    """Source-vs-engine: the feriados.tsv-derived (month, day) must equal
    both the engine's resolved 2024 date AND the .tab file's own args (a
    disagreement anywhere here is a BUG REPORT item, not silently aligned)."""
    src_month, src_day = _PT_MUNICIPAL_FIXED_SOURCE[(subdiv, name)]
    assert (src_month, src_day) == (month, day)
    got = _dates_for("PT", 2024, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(2024, month, day)


def test_pt_municipal_fixed_gold_count():
    assert len(_PT_MUNICIPAL_FIXED_TAB) == 224


# ==========================================================================
# PT municipal -- movable (source: feriados_moveis.tsv phrase table).
# ==========================================================================
def _nth_weekday_2024(month, n, weekday, post_offset=0):
    rec = nth_weekday_of_month(n, weekday, month=month)
    got = list(occurrences(rec, AstroDate(2024, 1, 1), until=AstroDate(2024, 12, 31)))
    return got[0].start + timedelta(days=post_offset)


#: Mirrors the documented conversions in feriados_moveis.tsv, NOT copied from
#: pt.tab -- see the module docstring for the two mapping bugs this caught
#: (and fixed here) before the two files agreed.
_MOVABLE_PHRASE_RULES = [
    (r"^Segunda-feira apos a Pascoa$", lambda: _E2024 + timedelta(days=1)),
    (r"^Segunda Segunda-feira apos a Pascoa", lambda: _E2024 + timedelta(days=8)),
    (r"^Terceira Segunda-feira apos a Pascoa", lambda: _E2024 + timedelta(days=15)),
    (r"^Terca-feira que segue o primeiro domingo depois da Pascoa",
     lambda: _E2024 + timedelta(days=9)),
    # "Quinta" = ordinal FIFTH (not fourth) Monday after Easter -- there is no
    # "Quarta Segunda-feira" row in the source, confirmed against pt.tab's 29.
    (r"^Quinta Segunda-feira apos a Pascoa", lambda: _E2024 + timedelta(days=29)),
    (r"^Sexta Quinta-feira apos o Domingo de Pascoa", lambda: _E2024 + timedelta(days=39)),
    (r"^Segunda-feira apos o Domingo de Pentecostes", lambda: _E2024 + timedelta(days=50)),
    (r"^Terca-Feira apos o Domingo de Pentecostes", lambda: _E2024 + timedelta(days=51)),
    (r"^Sexta-feira a seguir ao Dia de Corpo de Deus", lambda: _E2024 + timedelta(days=61)),
    (r"^Segunda-feira apos o segundo Domingo de Julho", lambda: _nth_weekday_2024(7, 2, 6, 1)),
    (r"^Segunda-feira apos o terceiro Domingo de Julho", lambda: _nth_weekday_2024(7, 3, 6, 1)),
    (r"^Segunda-feira apos o ultimo Domingo de Julho", lambda: _nth_weekday_2024(7, -1, 6, 1)),
    (r"^Segunda-feira apos o primeiro Domingo de Agosto", lambda: _nth_weekday_2024(8, 1, 6, 1)),
    (r"^Segunda-feira apos o segundo Domingo de Agosto", lambda: _nth_weekday_2024(8, 2, 6, 1)),
    (r"^Segunda-feira apos o terceiro Domingo de Agosto", lambda: _nth_weekday_2024(8, 3, 6, 1)),
    (r"^Segunda-feira apos o quarto Domingo de Agosto", lambda: _nth_weekday_2024(8, 4, 6, 1)),
    (r"^Segunda Sexta-feira de Setembro", lambda: _nth_weekday_2024(9, 2, 4)),
    (r"^Terca-feira apos o segundo Domingo de Setembro", lambda: _nth_weekday_2024(9, 2, 6, 2)),
    (r"^Segunda-feira apos o primeiro Domingo de Outubro", lambda: _nth_weekday_2024(10, 1, 6, 1)),
    # "the Monday AFTER that Saturday", i.e. +2 days from the Saturday, not +1.
    (r"^Segunda-feira apos o primeiro Sabado de Outubro", lambda: _nth_weekday_2024(10, 1, 5, 2)),
]


def _pt_movable_municipal_source_golds():
    """Parse feriados_moveis.tsv -> {subdiv: (AstroDate, name)}."""
    codes = _load_municipio_codes()
    out = {}
    path = os.path.join(_PAPERS, "feriados_moveis.tsv")
    with open(path, encoding="utf-8") as fh:
        next(fh)
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            data, feriado, muni_field = parts[0], parts[1].strip(), parts[2]
            data_folded = _fold(data.strip())
            rule_fn = None
            for pat, fn in _MOVABLE_PHRASE_RULES:
                if re.match(_fold(pat), data_folded):
                    rule_fn = fn
                    break
            assert rule_fn is not None, f"unrecognised feriados_moveis.tsv phrase: {data!r}"
            date = rule_fn()
            for n in _split_municipalities(muni_field):
                if n in _MUNI_NOT_A_CONCELHO:
                    continue
                code = _resolve_muni_code(n, codes)
                if code is None:
                    continue
                out[code] = (date, feriado)
    return out


_PT_MUNICIPAL_MOVABLE_SOURCE = _pt_movable_municipal_source_golds()
#: [(subdiv, kind, args, name)] -- no subdiv carries two movable rules (checked),
#: but kept as a list for the same reason as the fixed table above.
_PT_MUNICIPAL_MOVABLE_TAB = _load_pt_tab_municipal({"easter", "nth_weekday"})

for _subdiv, _kind, _args, _n in _PT_MUNICIPAL_MOVABLE_TAB:
    assert _subdiv in _PT_MUNICIPAL_MOVABLE_SOURCE, (
        f"{_subdiv} ({_n!r}) has no matching feriados_moveis.tsv row")
    _date, _ = _PT_MUNICIPAL_MOVABLE_SOURCE[_subdiv]
    _reg("PT", _subdiv, _n, 2024, _date.month, _date.day)


@pytest.mark.parametrize("subdiv,kind,args,name", sorted(_PT_MUNICIPAL_MOVABLE_TAB))
def test_pt_municipal_movable_gold_matches_source(subdiv, kind, args, name):
    """Source-vs-engine: the feriados_moveis.tsv phrase-derived date must
    equal the engine's resolved 2024 date. Disagreements are BUG REPORT
    items, not silently aligned (see the two caught during authoring, both
    traced to this file's phrase table rather than pt.tab -- module docstring)."""
    src_date, _ = _PT_MUNICIPAL_MOVABLE_SOURCE[subdiv]
    got = _dates_for("PT", 2024, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(src_date.year, src_date.month, src_date.day)


def test_pt_municipal_movable_gold_count():
    assert len(_PT_MUNICIPAL_MOVABLE_TAB) == 73


def test_pt_municipal_gold_total():
    assert len(_PT_MUNICIPAL_FIXED_TAB) + len(_PT_MUNICIPAL_MOVABLE_TAB) == 297


# ==========================================================================
# Wave 1a: GB, DE, FR, ES, BR, CA (national + subdivisions).
# Golds hand-derived from each country's cited primary source (see the .tab
# header + papers/holidays/INDEX.md); movable days re-derived here via
# easter(2024) + the documented offset (``_mov``), never read from the engine.
# Full sourcing, subdivision scope decisions, and the documented reference
# differential disagreements live in the per-country test modules
# (test_holidays_<cc>.py), which own the differential + behavioural assertions.
# ==========================================================================
def _mov(offset):
    """(2024, month, day) for a day at ``easter(2024) + offset`` (independent)."""
    d = _E2024 + timedelta(days=offset)
    return (2024, d.month, d.day)


# --- GB: UK bank holidays (source: gov.uk/bank-holidays) ---
_reg("GB", None, "New Year's Day", 2024, 1, 1)
_reg("GB", None, "Good Friday", *_mov(-2))
_reg("GB", None, "Early May Bank Holiday", 2024, 5, 6)   # 1st Monday of May
_reg("GB", None, "Spring Bank Holiday", 2024, 5, 27)     # last Monday of May
_reg("GB", None, "Christmas Day", 2024, 12, 25)
_reg("GB", None, "Boxing Day", 2024, 12, 26)
_reg("GB", "GB-EAW", "Easter Monday", *_mov(1))
_reg("GB", "GB-EAW", "Summer Bank Holiday", 2024, 8, 26)  # last Monday of Aug
_reg("GB", "GB-SCT", "2nd January", 2024, 1, 2)
_reg("GB", "GB-SCT", "Summer Bank Holiday", 2024, 8, 5)   # 1st Monday of Aug
_reg("GB", "GB-SCT", "St Andrew's Day", 2024, 11, 30)
_reg("GB", "GB-NIR", "St Patrick's Day", 2024, 3, 17)
_reg("GB", "GB-NIR", "Easter Monday", *_mov(1))
_reg("GB", "GB-NIR", "Battle of the Boyne", 2024, 7, 12)
_reg("GB", "GB-NIR", "Summer Bank Holiday", 2024, 8, 26)  # last Monday of Aug
# gov.uk substitute ("in-lieu") days (gb_substitute policy). The Christmas/Boxing
# cascade of 2021 and the New Year substitutes are the flagship golds; names carry
# the " (substitute day)" suffix the policy appends.
_reg("GB", None, "Christmas Day (substitute day)", 2021, 12, 27)
_reg("GB", None, "Boxing Day (substitute day)", 2021, 12, 28)
_reg("GB", None, "Christmas Day (substitute day)", 2022, 12, 27)
_reg("GB", None, "New Year's Day (substitute day)", 2022, 1, 3)
_reg("GB", None, "New Year's Day (substitute day)", 2023, 1, 2)
# One-off bank holidays (one_off kind): granted for a single year, never recur.
# Dates from gov.uk's per-year bank-holiday listing / proclamation news (cited in
# gb.tab's one_off rows). They resolve only in their stated year.
_reg("GB", None, "Platinum Jubilee bank holiday", 2022, 6, 3)
_reg("GB", None, "State Funeral of Queen Elizabeth II", 2022, 9, 19)
_reg("GB", None, "Coronation of King Charles III", 2023, 5, 8)

# --- DE: national nine + all 16 Länder (source: Land Feiertagsgesetze) ---
_reg("DE", None, "Neujahr", 2024, 1, 1)
_reg("DE", None, "Karfreitag", *_mov(-2))
_reg("DE", None, "Ostermontag", *_mov(1))
_reg("DE", None, "Erster Mai", 2024, 5, 1)
_reg("DE", None, "Christi Himmelfahrt", *_mov(39))
_reg("DE", None, "Pfingstmontag", *_mov(50))
_reg("DE", None, "Tag der Deutschen Einheit", 2024, 10, 3)
_reg("DE", None, "Erster Weihnachtstag", 2024, 12, 25)
_reg("DE", None, "Zweiter Weihnachtstag", 2024, 12, 26)
for _s in ("DE-BW", "DE-BY", "DE-ST"):
    _reg("DE", _s, "Heilige Drei Könige", 2024, 1, 6)
for _s in ("DE-BE", "DE-MV"):
    _reg("DE", _s, "Internationaler Frauentag", 2024, 3, 8)
_reg("DE", "DE-BB", "Ostersonntag", *_mov(0))
_reg("DE", "DE-BB", "Pfingstsonntag", *_mov(49))
for _s in ("DE-BW", "DE-BY", "DE-HE", "DE-NW", "DE-RP", "DE-SL"):
    _reg("DE", _s, "Fronleichnam", *_mov(60))
_reg("DE", "DE-SL", "Mariä Himmelfahrt", 2024, 8, 15)
_reg("DE", "DE-TH", "Weltkindertag", 2024, 9, 20)
for _s in ("DE-BB", "DE-HB", "DE-HH", "DE-MV", "DE-NI", "DE-SN", "DE-ST",
           "DE-SH", "DE-TH"):
    _reg("DE", _s, "Reformationstag", 2024, 10, 31)
for _s in ("DE-BW", "DE-BY", "DE-NW", "DE-RP", "DE-SL"):
    _reg("DE", _s, "Allerheiligen", 2024, 11, 1)
_reg("DE", "DE-SN", "Buß- und Bettag", 2024, 11, 20)  # Wed on/before 22 Nov

# --- FR: 11 national + Alsace-Moselle extras (source: service-public.fr) ---
_reg("FR", None, "Jour de l'an", 2024, 1, 1)
_reg("FR", None, "Lundi de Pâques", *_mov(1))
_reg("FR", None, "Fête du Travail", 2024, 5, 1)
_reg("FR", None, "Fête de la Victoire", 2024, 5, 8)
_reg("FR", None, "Ascension", *_mov(39))
_reg("FR", None, "Lundi de Pentecôte", *_mov(50))
_reg("FR", None, "Fête nationale", 2024, 7, 14)
_reg("FR", None, "Assomption", 2024, 8, 15)
_reg("FR", None, "Toussaint", 2024, 11, 1)
_reg("FR", None, "Armistice 1918", 2024, 11, 11)
_reg("FR", None, "Noël", 2024, 12, 25)
for _s in ("FR-57", "FR-6AE"):
    _reg("FR", _s, "Vendredi saint", *_mov(-2))
    _reg("FR", _s, "Saint Étienne", 2024, 12, 26)

# --- ES: national fixed set only (source: Estatuto de los Trabajadores) ---
_reg("ES", None, "Año Nuevo", 2024, 1, 1)
_reg("ES", None, "Epifanía del Señor", 2024, 1, 6)
_reg("ES", None, "Viernes Santo", *_mov(-2))
_reg("ES", None, "Fiesta del Trabajo", 2024, 5, 1)
_reg("ES", None, "Asunción de la Virgen", 2024, 8, 15)
_reg("ES", None, "Fiesta Nacional de España", 2024, 10, 12)
_reg("ES", None, "Todos los Santos", 2024, 11, 1)
_reg("ES", None, "Día de la Constitución Española", 2024, 12, 6)
_reg("ES", None, "Inmaculada Concepción", 2024, 12, 9)  # Sun 8 Dec -> Mon 9 (sun_mon)
_reg("ES", None, "Natividad del Señor", 2024, 12, 25)
# National Sunday traslado outcomes, each verified against the cited BOE
# "relación de fiestas laborales" resolution for that year (see es.tab header).
_reg("ES", None, "Año Nuevo", 2023, 1, 2)                     # BOE-A-2022-16755
_reg("ES", None, "Fiesta Nacional de España", 2025, 10, 13)  # BOE-A-2024-21316
_reg("ES", None, "Todos los Santos", 2026, 11, 2)            # BOE-A-2025-21667
_reg("ES", None, "Día de la Constitución Española", 2026, 12, 7)  # BOE-A-2025-21667

# --- BR: national feriados + facultative Carnaval/Corpus (source: Planalto) ---
_reg("BR", None, "Confraternização Universal", 2024, 1, 1)
_reg("BR", None, "Sexta-feira Santa", *_mov(-2))
_reg("BR", None, "Tiradentes", 2024, 4, 21)
_reg("BR", None, "Dia do Trabalhador", 2024, 5, 1)
_reg("BR", None, "Independência do Brasil", 2024, 9, 7)
_reg("BR", None, "Nossa Senhora Aparecida", 2024, 10, 12)
_reg("BR", None, "Finados", 2024, 11, 2)
_reg("BR", None, "Proclamação da República", 2024, 11, 15)
_reg("BR", None, "Dia Nacional de Zumbi e da Consciência Negra", 2024, 11, 20)
_reg("BR", None, "Natal", 2024, 12, 25)
_reg("BR", None, "Carnaval", *_mov(-47))
_reg("BR", None, "Corpus Christi", *_mov(60))
_reg("BR", "BR-SP", "Revolução Constitucionalista", 2024, 7, 9)
_reg("BR", "BR-RJ", "São Jorge", 2024, 4, 23)

# --- CA: federal + compact provincial sample (source: Holidays Act + provinces) ---
_reg("CA", None, "New Year's Day", 2024, 1, 1)
_reg("CA", None, "Good Friday", *_mov(-2))
_reg("CA", None, "Canada Day", 2024, 7, 1)
_reg("CA", None, "Labour Day", 2024, 9, 2)               # 1st Monday of Sept
_reg("CA", None, "Christmas Day", 2024, 12, 25)
_reg("CA", "CA-ON", "Family Day", 2024, 2, 19)           # 3rd Monday of Feb
_reg("CA", "CA-ON", "Victoria Day", 2024, 5, 20)         # Monday preceding 25 May
_reg("CA", "CA-ON", "Thanksgiving Day", 2024, 10, 14)    # 2nd Monday of Oct
_reg("CA", "CA-ON", "Boxing Day", 2024, 12, 26)
_reg("CA", "CA-QC", "National Patriots' Day", 2024, 5, 20)
_reg("CA", "CA-QC", "Saint-Jean-Baptiste", 2024, 6, 24)
_reg("CA", "CA-QC", "Thanksgiving Day", 2024, 10, 14)
_reg("CA", "CA-BC", "Family Day", 2024, 2, 19)
_reg("CA", "CA-BC", "Victoria Day", 2024, 5, 20)
_reg("CA", "CA-BC", "British Columbia Day", 2024, 8, 5)  # 1st Monday of Aug
_reg("CA", "CA-BC", "National Day for Truth and Reconciliation", 2024, 9, 30)
_reg("CA", "CA-BC", "Thanksgiving Day", 2024, 10, 14)
_reg("CA", "CA-BC", "Remembrance Day", 2024, 11, 11)
_reg("CA", "CA-AB", "Family Day", 2024, 2, 19)
_reg("CA", "CA-AB", "Victoria Day", 2024, 5, 20)
_reg("CA", "CA-AB", "Thanksgiving Day", 2024, 10, 14)
_reg("CA", "CA-AB", "Remembrance Day", 2024, 11, 11)
_reg("CA", "CA-MB", "Louis Riel Day", 2024, 2, 19)
_reg("CA", "CA-MB", "Victoria Day", 2024, 5, 20)
_reg("CA", "CA-MB", "National Day for Truth and Reconciliation", 2024, 9, 30)
_reg("CA", "CA-MB", "Thanksgiving Day", 2024, 10, 14)
_reg("CA", "CA-NS", "Heritage Day", 2024, 2, 19)
_reg("CA", "CA-NS", "Remembrance Day", 2024, 11, 11)


# ==========================================================================
# ES autonomous-community layer -- golds parsed from the four cited BOE tables
# (source-vs-engine, the same discipline as PT municipal): the expected dates
# come from the BOE HTML, not from es.tab's own args.
# ==========================================================================
_ES_CODES = ["ES-AN", "ES-AR", "ES-AS", "ES-IB", "ES-CN", "ES-CB", "ES-CM",
             "ES-CL", "ES-CT", "ES-EX", "ES-GA", "ES-MD", "ES-MC", "ES-NC",
             "ES-PV", "ES-RI", "ES-VC", "ES-CE", "ES-ML"]
_ES_MONTHS = {m.lower(): i for i, m in enumerate(
    ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto",
     "Septiembre", "Octubre", "Noviembre", "Diciembre"], 1)}
_ES_BOE = {2023: "es_boe_BOE-A-2022-16755.html",
           2024: "es_boe_BOE-A-2023-22014.html",
           2025: "es_boe_BOE-A-2024-21316.html",
           2026: "es_boe_BOE-A-2025-21667.html"}


def _es_canon(n):
    """Map a BOE row name to the es.tab regional rule name; None = drop (a
    nationwide holiday or a national-holiday Sunday traslado, handled elsewhere)."""
    if n.startswith("Lunes siguiente") or n.startswith("Día siguiente"):
        if "Asturias" in n:
            return "Día de Asturias"
        if "Illes Balears" in n:
            return "Día de les Illes Balears"
        if "Rioja" in n:
            return "Día de La Rioja"
        if "San Jorge" in n:
            return "San Jorge/Día de Aragón"
        if "San José" in n:
            return "San José"
        return None
    if "Rioja" in n:
        return "Día de La Rioja"
    if "Sacrificio" in n or "Adha" in n:
        return "Fiesta del Sacrificio (Aid al-Adha)"
    if "Eid Fitr" in n or "Eid al-Fitr" in n:
        return "Fiesta del Aid al-Fitr"
    if n.startswith("Corpus") or n.startswith("Fiesta del Corpus"):
        return "Corpus Christi"
    return n


def _es_regional_source_golds():
    """Parse the four BOE tables into {(subdiv, name, year): (month, day)} for the
    community-specific holidays (markers ** / *** that are not nationwide)."""
    out = {}
    for year, fn in _ES_BOE.items():
        path = os.path.join(_PAPERS, fn)
        html_text = open(path, encoding="utf-8").read()
        m = re.search(r'<table class="tabla_girada_condensada">(.*?)</table>',
                      html_text, re.S)
        rows = re.findall(r"<tr[^>]*>(.*?)</tr>", m.group(1), re.S)
        curm = None
        for r in rows:
            cells = [re.sub(r"<[^>]+>", "", c).strip()
                     for c in re.findall(r"<t[hd][^>]*>(.*?)</t[hd]>", r, re.S)]
            import html as _h
            cells = [_h.unescape(c) for c in cells]
            if not cells:
                continue
            if cells[0].lower() in _ES_MONTHS:
                curm = _ES_MONTHS[cells[0].lower()]
                continue
            mm = re.match(r"(\d+)\s+(.*)", cells[0])
            if not mm or curm is None:
                continue
            day = int(mm.group(1))
            name = mm.group(2).rstrip(".").strip()
            marks = {_ES_CODES[i]: v for i, v in enumerate(cells[1:])
                     if i < 19 and v in ("*", "**", "***")}
            if len(marks) == 19:  # nationwide -> not a regional extra
                continue
            base = _es_canon(name)
            if base is None:
                continue
            for sub in marks:
                out[(sub, base, year)] = (curm, day)
    return out


_ES_REGIONAL_SOURCE = _es_regional_source_golds()
for (_sub, _name, _yr), (_m, _d) in _ES_REGIONAL_SOURCE.items():
    _reg("ES", _sub, _name, _yr, _m, _d)


@pytest.mark.parametrize("subdiv,name,year,month,day", sorted(
    (s, n, y, m, d) for (s, n, y), (m, d) in _ES_REGIONAL_SOURCE.items()))
def test_es_regional_gold_matches_boe_source(subdiv, name, year, month, day):
    """Source-vs-engine: the BOE-table date must equal the engine's decree
    resolution for that community and year."""
    got = _dates_for("ES", year, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(year, month, day)


def test_es_regional_covers_all_communities():
    assert {s for (s, _n, _y) in _ES_REGIONAL_SOURCE} == set(_ES_CODES)


@pytest.mark.parametrize("country,subdiv,name,year,month,day", [
    (c, s, n, y, m, d)
    for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c in {"GB", "DE", "FR", "ES", "BR", "CA"}
    for (y, m, d) in ymds
])
def test_w1a_gold(country, subdiv, name, year, month, day):
    got = _dates_for(country, year, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(year, month, day)


# ==========================================================================
# Wave 1b: AU, IN, CN, JP, TR, IL.
# Golds hand-derived from each country's cited primary source (see the .tab
# header + papers/holidays/INDEX.md). Independence properties preserved:
#   * Easter-relative movables (Good Friday / Easter Monday) re-derived via
#     ``_mov`` from ``easter(2024)``, never read from the engine.
#   * nth-weekday movables carry the rule in a comment; the literal is the
#     source's own published date, not the .tab arg.
#   * Equinox golds (JP Shunbun/Shubun) are the Cabinet Office's PUBLISHED
#     dates, independent of chronologia's equinox arithmetic.
#   * Decree golds (AU WA King's Birthday proclamations; IN Hindu/Buddhist/
#     Sikh/Jain lunisolar) are the per-year gazette/proclamation dates.
#   * Islamic and lunisolar calendar_date golds are the source announcements'
#     published dates (State Council / official listings), independent of the
#     engine's calendar conversion.
# The differential vs the vacanza `holidays` package and the behavioural
# assertions live in test_civil_holidays_w1b.py (this batch's per-country
# module), including the Islamic +/-1 caveat and the 调休/振替休日 out-of-scope
# adjudications.
# ==========================================================================
# --- AU: national + state/territory (source: Fair Work + WA proclamations) ---
_reg("AU", None, "New Year's Day", 2024, 1, 1)
_reg("AU", None, "Australia Day", 2024, 1, 26)
_reg("AU", None, "Australia Day", 2025, 1, 27)   # 2025-01-26 Sun -> Mon (sat_sun_mon)
_reg("AU", None, "Good Friday", *_mov(-2))
_reg("AU", None, "Easter Monday", *_mov(1))
_reg("AU", None, "ANZAC Day", 2024, 4, 25)
_reg("AU", None, "Christmas Day", 2024, 12, 25)
_reg("AU", None, "Boxing Day", 2024, 12, 26)
_reg("AU", "AU-NSW", "King's Birthday", 2024, 6, 10)     # 2nd Mon Jun
_reg("AU", "AU-NSW", "Labour Day", 2024, 10, 7)          # 1st Mon Oct
_reg("AU", "AU-VIC", "King's Birthday", 2024, 6, 10)
_reg("AU", "AU-VIC", "Labour Day", 2024, 3, 11)          # 2nd Mon Mar
_reg("AU", "AU-VIC", "Melbourne Cup Day", 2024, 11, 5)   # 1st Tue Nov
_reg("AU", "AU-QLD", "King's Birthday", 2024, 10, 7)     # 1st Mon Oct
_reg("AU", "AU-QLD", "Labour Day", 2024, 5, 6)           # 1st Mon May
_reg("AU", "AU-WA", "King's Birthday", 2023, 9, 25)      # proclaimed (decree)
_reg("AU", "AU-WA", "King's Birthday", 2024, 9, 23)
_reg("AU", "AU-WA", "King's Birthday", 2025, 9, 29)
_reg("AU", "AU-WA", "Western Australia Day", 2024, 6, 3)  # 1st Mon Jun
_reg("AU", "AU-WA", "Labour Day", 2024, 3, 4)            # 1st Mon Mar
_reg("AU", "AU-SA", "King's Birthday", 2024, 6, 10)
_reg("AU", "AU-SA", "Labour Day", 2024, 10, 7)
_reg("AU", "AU-TAS", "King's Birthday", 2024, 6, 10)
_reg("AU", "AU-TAS", "Eight Hours Day", 2024, 3, 11)     # 2nd Mon Mar
_reg("AU", "AU-ACT", "King's Birthday", 2024, 6, 10)
_reg("AU", "AU-ACT", "Labour Day", 2024, 10, 7)
_reg("AU", "AU-ACT", "Canberra Day", 2024, 3, 11)        # 2nd Mon Mar
_reg("AU", "AU-NT", "King's Birthday", 2024, 6, 10)
_reg("AU", "AU-NT", "May Day", 2024, 5, 6)               # 1st Mon May
_reg("AU", "AU-NT", "Picnic Day", 2024, 8, 5)            # 1st Mon Aug

# --- IN: central gazetted (source: MHA/DoPT gazette) ---
_reg("IN", None, "Republic Day", 2024, 1, 26)
_reg("IN", None, "Republic Day", 2025, 1, 26)
_reg("IN", None, "Independence Day", 2024, 8, 15)
_reg("IN", None, "Mahatma Gandhi's Jayanti", 2024, 10, 2)
_reg("IN", None, "Christmas", 2024, 12, 25)
_reg("IN", None, "Good Friday", *_mov(-2))
# Islamic (islamic_civil tabular; gazette can differ +/-1, see w1b module)
_reg("IN", None, "Id-ul-Fitr", 2024, 4, 10)
_reg("IN", None, "Id-ul-Zuha (Bakrid)", 2024, 6, 17)
_reg("IN", None, "Muharram", 2024, 7, 17)
_reg("IN", None, "Milad-un-Nabi", 2024, 9, 16)
# Hindu/Buddhist/Sikh/Jain lunisolar (per-year gazette decree dates)
_reg("IN", None, "Holi", 2023, 3, 8)
_reg("IN", None, "Holi", 2024, 3, 25)
_reg("IN", None, "Ram Navami", 2024, 4, 17)
_reg("IN", None, "Mahavir Jayanti", 2024, 4, 21)
_reg("IN", None, "Buddha Purnima", 2024, 5, 23)
_reg("IN", None, "Janmashtami", 2024, 8, 26)
_reg("IN", None, "Dussehra", 2024, 10, 12)
_reg("IN", None, "Diwali (Deepavali)", 2024, 10, 31)
_reg("IN", None, "Diwali (Deepavali)", 2025, 10, 20)
_reg("IN", None, "Guru Nanak's Jayanti", 2024, 11, 15)
_reg("IN", None, "Maha Shivaratri", 2024, 3, 8)

# --- CN: statutory list (source: State Council). Primary names are the official
#     Chinese (zh) names; English is carried in `names`. ---
_reg("CN", None, "元旦", 2024, 1, 1)          # New Year's Day
_reg("CN", None, "劳动节", 2024, 5, 1)         # Labour Day
_reg("CN", None, "国庆节", 2024, 10, 1)        # National Day
_reg("CN", None, "国庆节假期", 2024, 10, 2)     # National Day Holiday
_reg("CN", None, "国庆节假期", 2024, 10, 3)
_reg("CN", None, "春节", 2024, 2, 10)         # Spring Festival
_reg("CN", None, "春节", 2025, 1, 29)
_reg("CN", None, "春节假期", 2024, 2, 11)      # Spring Festival Holiday
_reg("CN", None, "春节假期", 2024, 2, 12)
_reg("CN", None, "端午节", 2024, 6, 10)        # Dragon Boat Festival
_reg("CN", None, "中秋节", 2024, 9, 17)        # Mid-Autumn Festival
_reg("CN", None, "清明节", 2023, 4, 5)         # Qingming — solar term
_reg("CN", None, "清明节", 2024, 4, 4)
_reg("CN", None, "清明节", 2025, 4, 4)

# --- JP: national holidays (source: Cabinet Office). Primary names are the
#     official Japanese (ja) names; English is carried in `names`. ---
_reg("JP", None, "元日", 2024, 1, 1)                # New Year's Day
_reg("JP", None, "建国記念の日", 2024, 2, 11)          # National Foundation Day
_reg("JP", None, "天皇誕生日", 2024, 2, 23)           # Emperor's Birthday
_reg("JP", None, "昭和の日", 2024, 4, 29)            # Showa Day
_reg("JP", None, "憲法記念日", 2024, 5, 3)            # Constitution Memorial Day
_reg("JP", None, "みどりの日", 2024, 5, 4)            # Greenery Day
_reg("JP", None, "こどもの日", 2024, 5, 5)            # Children's Day
_reg("JP", None, "山の日", 2024, 8, 11)             # Mountain Day
_reg("JP", None, "文化の日", 2024, 11, 3)            # Culture Day
_reg("JP", None, "勤労感謝の日", 2024, 11, 23)         # Labour Thanksgiving Day
_reg("JP", None, "成人の日", 2024, 1, 8)             # Coming of Age Day — 2nd Mon Jan
_reg("JP", None, "成人の日", 2025, 1, 13)
_reg("JP", None, "海の日", 2024, 7, 15)             # Marine Day — 3rd Mon Jul
_reg("JP", None, "敬老の日", 2024, 9, 16)            # Respect for the Aged — 3rd Mon Sep
_reg("JP", None, "スポーツの日", 2024, 10, 14)        # Sports Day — 2nd Mon Oct
_reg("JP", None, "春分の日", 2024, 3, 20)            # Vernal Equinox — CAO published
_reg("JP", None, "春分の日", 2025, 3, 20)
_reg("JP", None, "秋分の日", 2024, 9, 22)            # Autumnal Equinox — CAO published
_reg("JP", None, "秋分の日", 2025, 9, 23)
# 振替休日 furikae substitutes (jp_furikae policy): a Sunday holiday grants the
# following non-holiday day. 2024 Cabinet Office substitute days.
_reg("JP", None, "建国記念の日 (振替休日)", 2024, 2, 12)
_reg("JP", None, "こどもの日 (振替休日)", 2024, 5, 6)
_reg("JP", None, "山の日 (振替休日)", 2024, 8, 12)
_reg("JP", None, "秋分の日 (振替休日)", 2024, 9, 23)
_reg("JP", None, "文化の日 (振替休日)", 2024, 11, 4)

# --- TR: public holidays (source: Act 2429) ---
# Names are the official Turkish spellings, with full diacritics.
_reg("TR", None, "Yılbaşı", 2024, 1, 1)
_reg("TR", None, "Ulusal Egemenlik ve Çocuk Bayramı", 2024, 4, 23)
_reg("TR", None, "Emek ve Dayanışma Günü", 2024, 5, 1)
_reg("TR", None, "Atatürk'ü Anma, Gençlik ve Spor Bayramı", 2024, 5, 19)
_reg("TR", None, "Demokrasi ve Millî Birlik Günü", 2024, 7, 15)
_reg("TR", None, "Zafer Bayramı", 2024, 8, 30)
_reg("TR", None, "Cumhuriyet Bayramı", 2024, 10, 29)
_reg("TR", None, "Cumhuriyet Bayramı", 2025, 10, 29)
_reg("TR", None, "Ramazan Bayramı", 2024, 4, 10)   # 1 Shawwal (islamic_civil)
_reg("TR", None, "Ramazan Bayramı", 2025, 3, 31)
_reg("TR", None, "Kurban Bayramı", 2024, 6, 17)    # 10 Dhu al-Hijja (islamic_civil)

# --- IL: Hebrew-calendar holidays (source: Israeli official listing) ---
# Primary names are the official Hebrew (he) names; English is carried in `names`.
_reg("IL", None, "ראש השנה", 2024, 10, 3)          # Rosh Hashanah — Tishrei 1
_reg("IL", None, "ראש השנה", 2024, 10, 4)          # Tishrei 2
_reg("IL", None, "ראש השנה", 2025, 9, 23)
_reg("IL", None, "יום כיפור", 2024, 10, 12)        # Yom Kippur
_reg("IL", None, "סוכות", 2024, 10, 17)            # Sukkot
_reg("IL", None, "שמיני עצרת / שמחת תורה", 2024, 10, 24)  # Shemini Atzeret / Simchat Torah
_reg("IL", None, "פסח", 2024, 4, 23)               # Pesach
_reg("IL", None, "פסח", 2025, 4, 13)
_reg("IL", None, "שביעי של פסח", 2024, 4, 29)      # Pesach (Seventh Day)
_reg("IL", None, "שבועות", 2024, 6, 12)            # Shavuot
_reg("IL", None, "יום העצמאות", 2024, 5, 14)       # Yom Ha'atzmaut — Iyar 5 (Mon) -> Tue
_reg("IL", None, "יום העצמאות", 2025, 5, 1)        # Iyar 5 (Sat) -> Thu (postponed)


def _dateset_for(country, year, subdiv=None):
    """{(name, subdiv): {dates}} — a set per rule, so a name that resolves to
    several dates in one year (Rosh Hashanah's two days, a multi-day feast) is
    not collapsed the way ``_dates_for`` would."""
    out = {}
    for h in holidays_for(country, year, subdiv=subdiv):
        out.setdefault((h.name, h.subdiv), set()).add(h.date)
    return out


@pytest.mark.parametrize("country,subdiv,name,year,month,day", [
    (c, s, n, y, m, d)
    for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c in {"AU", "IN", "CN", "JP", "TR", "IL"}
    for (y, m, d) in ymds
])
def test_w1b_gold(country, subdiv, name, year, month, day):
    got = _dateset_for(country, year, subdiv=subdiv)
    assert AstroDate(year, month, day) in got.get((name, subdiv), set()), (
        f"{country}/{subdiv}/{name!r} {year}: expected "
        f"{year}-{month:02d}-{day:02d}, got "
        f"{sorted(got.get((name, subdiv), set()))}")


def test_jp_mountain_day_year_gated_from_2016():
    """Mountain Day (山の日) — established by the 2014 amendment, in force from
    2016 (jp.tab "2016-"): absent 2015, present from 2016."""
    assert ("山の日", None) not in _dates_for("JP", 2015)
    assert _dates_for("JP", 2016)[("山の日", None)] == AstroDate(2016, 8, 11)


# ==========================================================================
# Wave 2 (t2a): IT, GR, IE, AT, CH, BE, NL, PL, CZ, SK, SE, DK, NO, FI.
# Golds hand-derived from each country's cited primary source (see the .tab
# header + papers/holidays/INDEX.md). Easter-relative movables re-derived via
# ``_mov`` from ``easter(2024)``; Orthodox-Easter (GR) movables via
# ``_orth`` from the Julian-reckoned computus, never read from the engine.
# Per-country differential + behavioural assertions live in test_holidays_<cc>.py.
# ==========================================================================
_T2A = {"IT", "GR", "IE", "AT", "CH", "BE", "NL", "PL", "CZ", "SK",
        "SE", "DK", "NO", "FI"}

_ORTH2024 = easter(2024, "julian_gregorian_date")


def _orth(offset):
    """(2024, month, day) for ``orthodox_easter(2024) + offset`` (independent)."""
    d = _ORTH2024 + timedelta(days=offset)
    return (2024, d.month, d.day)


# --- IT: national festività (L.260/1949) + 20 regional-capital patrons ---
_reg("IT", None, "Capodanno", 2024, 1, 1)
_reg("IT", None, "Epifania", 2024, 1, 6)
_reg("IT", None, "Pasqua", *_mov(0))
_reg("IT", None, "Lunedì dell'Angelo", *_mov(1))
_reg("IT", None, "Anniversario della Liberazione", 2024, 4, 25)
_reg("IT", None, "Festa del Lavoro", 2024, 5, 1)
_reg("IT", None, "Festa della Repubblica", 2024, 6, 2)
_reg("IT", None, "Assunzione della Beata Vergine Maria", 2024, 8, 15)
_reg("IT", None, "Ognissanti", 2024, 11, 1)
_reg("IT", None, "Immacolata Concezione", 2024, 12, 8)
_reg("IT", None, "Natale", 2024, 12, 25)
_reg("IT", None, "Santo Stefano", 2024, 12, 26)
# Regional-capital patron feasts (municipal): (subdiv, name, month, day).
_IT_PATRONS = [
    ("IT-TO", "San Giovanni Battista", 6, 24),
    ("IT-AO", "San Grato", 9, 7),
    ("IT-MI", "Sant'Ambrogio", 12, 7),
    ("IT-TN", "San Vigilio", 6, 26),
    ("IT-VE", "Madonna della Salute", 11, 21),
    ("IT-TS", "San Giusto", 11, 3),
    ("IT-GE", "San Giovanni Battista", 6, 24),
    ("IT-BO", "San Petronio", 10, 4),
    ("IT-FI", "San Giovanni Battista", 6, 24),
    ("IT-PG", "San Costanzo", 1, 29),
    ("IT-AN", "San Ciriaco", 5, 4),
    ("IT-RM", "Santi Pietro e Paolo", 6, 29),
    ("IT-AQ", "San Massimo d'Aveia", 6, 10),
    ("IT-CB", "San Giorgio", 4, 23),
    ("IT-NA", "San Gennaro", 9, 19),
    ("IT-BA", "San Nicola", 12, 6),
    ("IT-PZ", "San Gerardo di Potenza", 5, 30),
    ("IT-CZ", "San Vitaliano", 7, 16),
    ("IT-PA", "Santa Rosalia", 7, 15),
    ("IT-CA", "San Saturnino di Cagliari", 10, 30),
]
for _s, _n, _m, _d in _IT_PATRONS:
    _reg("IT", _s, _n, 2024, _m, _d)


# --- GR: Orthodox-Easter national set (native Greek names) ---
_reg("GR", None, "Πρωτοχρονιά", 2024, 1, 1)
_reg("GR", None, "Θεοφάνεια", 2024, 1, 6)
_reg("GR", None, "Καθαρά Δευτέρα", *_orth(-48))   # 2024-03-18
_reg("GR", None, "Εικοστή Πέμπτη Μαρτίου", 2024, 3, 25)
_reg("GR", None, "Μεγάλη Παρασκευή", *_orth(-2))  # 2024-05-03
_reg("GR", None, "Δευτέρα του Πάσχα", *_orth(1))  # 2024-05-06
_reg("GR", None, "Εργατική Πρωτομαγιά", 2024, 5, 1)
_reg("GR", None, "Δευτέρα του Αγίου Πνεύματος", *_orth(50))  # 2024-06-24
_reg("GR", None, "Κοίμηση της Θεοτόκου", 2024, 8, 15)
_reg("GR", None, "Ημέρα του Όχι", 2024, 10, 28)
_reg("GR", None, "Χριστούγεννα", 2024, 12, 25)
_reg("GR", None, "Σύναξη της Υπεραγίας Θεοτόκου", 2024, 12, 26)
# Cross-year Orthodox-Easter movables (independent Julian computus):
# 2023 Orthodox Easter 16 Apr -> Clean Monday 27 Feb; 2025 20 Apr -> 3 Mar.
_reg("GR", None, "Καθαρά Δευτέρα", 2023, 2, 27)
_reg("GR", None, "Καθαρά Δευτέρα", 2025, 3, 3)


# --- IE: public holidays (Organisation of Working Time Act 1997) ---
_reg("IE", None, "New Year's Day", 2024, 1, 1)
_reg("IE", None, "Saint Brigid's Day", 2024, 2, 5)   # 1st Mon Feb
_reg("IE", None, "Saint Brigid's Day", 2023, 2, 6)
_reg("IE", None, "Saint Brigid's Day", 2025, 2, 3)
_reg("IE", None, "Saint Patrick's Day", 2024, 3, 17)
_reg("IE", None, "Easter Monday", *_mov(1))
_reg("IE", None, "May Day", 2024, 5, 6)              # 1st Mon May
_reg("IE", None, "June Bank Holiday", 2024, 6, 3)    # 1st Mon Jun
_reg("IE", None, "August Bank Holiday", 2024, 8, 5)  # 1st Mon Aug
_reg("IE", None, "October Bank Holiday", 2024, 10, 28)  # last Mon Oct
_reg("IE", None, "Christmas Day", 2024, 12, 25)
_reg("IE", None, "Saint Stephen's Day", 2024, 12, 26)
_reg("IE", None, "Day of Remembrance and Recognition", 2022, 3, 18)  # one_off


# --- AT: nationwide 13 (ARG §7) + Landespatrone (regional) ---
_reg("AT", None, "Neujahr", 2024, 1, 1)
_reg("AT", None, "Heilige Drei Könige", 2024, 1, 6)
_reg("AT", None, "Ostermontag", *_mov(1))
_reg("AT", None, "Staatsfeiertag", 2024, 5, 1)
_reg("AT", None, "Christi Himmelfahrt", *_mov(39))
_reg("AT", None, "Pfingstmontag", *_mov(50))
_reg("AT", None, "Fronleichnam", *_mov(60))
_reg("AT", None, "Mariä Himmelfahrt", 2024, 8, 15)
_reg("AT", None, "Nationalfeiertag", 2024, 10, 26)
_reg("AT", None, "Allerheiligen", 2024, 11, 1)
_reg("AT", None, "Mariä Empfängnis", 2024, 12, 8)
_reg("AT", None, "Christtag", 2024, 12, 25)
_reg("AT", None, "Stephanstag", 2024, 12, 26)
for _s in ("AT-6", "AT-7", "AT-8"):
    _reg("AT", _s, "Heiliger Josef", 2024, 3, 19)
_reg("AT", "AT-4", "Heiliger Florian", 2024, 5, 4)
_reg("AT", "AT-5", "Heiliger Rupert", 2024, 9, 24)
_reg("AT", "AT-2", "Tag der Volksabstimmung", 2024, 10, 10)
_reg("AT", "AT-1", "Heiliger Martin", 2024, 11, 11)
for _s in ("AT-3", "AT-9"):
    _reg("AT", _s, "Heiliger Leopold", 2024, 11, 15)


# --- CH: de-facto national 4 + documented 6-canton sample ---
_reg("CH", None, "Neujahrstag", 2024, 1, 1)
_reg("CH", None, "Auffahrt", *_mov(39))
_reg("CH", None, "Nationalfeiertag", 2024, 8, 1)
_reg("CH", None, "Weihnachten", 2024, 12, 25)
# Cantonal (2024): movables via _mov, fixed literal.
_CH_GF, _CH_EM, _CH_WM, _CH_FL = _mov(-2), _mov(1), _mov(50), _mov(60)
for _s in ("CH-ZH", "CH-BE", "CH-LU", "CH-GE"):
    _reg("CH", _s, "Karfreitag", *_CH_GF)
for _s in ("CH-ZH", "CH-BE", "CH-LU", "CH-TI", "CH-GE"):
    _reg("CH", _s, "Ostermontag", *_CH_EM)
for _s in ("CH-ZH", "CH-BE", "CH-LU", "CH-TI", "CH-GE"):
    _reg("CH", _s, "Pfingstmontag", *_CH_WM)
for _s in ("CH-ZH", "CH-TI"):
    _reg("CH", _s, "Tag der Arbeit", 2024, 5, 1)
for _s in ("CH-ZH", "CH-BE", "CH-LU", "CH-TI"):
    _reg("CH", _s, "Stephanstag", 2024, 12, 26)
for _s in ("CH-BE", "CH-LU"):
    _reg("CH", _s, "Berchtoldstag", 2024, 1, 2)
for _s in ("CH-LU", "CH-TI", "CH-VS"):
    _reg("CH", _s, "Fronleichnam", *_CH_FL)
for _s in ("CH-LU", "CH-TI", "CH-VS"):
    _reg("CH", _s, "Mariä Himmelfahrt", 2024, 8, 15)
    _reg("CH", _s, "Allerheiligen", 2024, 11, 1)
    _reg("CH", _s, "Mariä Empfängnis", 2024, 12, 8)
for _s in ("CH-TI", "CH-VS"):
    _reg("CH", _s, "Josefstag", 2024, 3, 19)
_reg("CH", "CH-TI", "Heilige Drei Könige", 2024, 1, 6)
_reg("CH", "CH-TI", "Peter und Paul", 2024, 6, 29)
_reg("CH", "CH-GE", "Jeûne genevois", 2024, 9, 5)   # Thu after 1st Sun Sep
_reg("CH", "CH-GE", "Restauration de la République", 2024, 12, 31)# --- BE: 10 legal holidays (KB 18 April 1974, Dutch names) ---
_reg("BE", None, "Nieuwjaar", 2024, 1, 1)
_reg("BE", None, "Paasmaandag", *_mov(1))
_reg("BE", None, "Dag van de Arbeid", 2024, 5, 1)
_reg("BE", None, "O. L. H. Hemelvaart", *_mov(39))
_reg("BE", None, "Pinkstermaandag", *_mov(50))
_reg("BE", None, "Nationale feestdag", 2024, 7, 21)
_reg("BE", None, "O. L. V. Hemelvaart", 2024, 8, 15)
_reg("BE", None, "Allerheiligen", 2024, 11, 1)
_reg("BE", None, "Wapenstilstand", 2024, 11, 11)
_reg("BE", None, "Kerstmis", 2024, 12, 25)

# --- NL: official holidays (Dutch names); Koningsdag shift ---
_reg("NL", None, "Nieuwjaarsdag", 2024, 1, 1)
_reg("NL", None, "Goede Vrijdag", *_mov(-2))
_reg("NL", None, "Eerste paasdag", *_mov(0))
_reg("NL", None, "Tweede paasdag", *_mov(1))
_reg("NL", None, "Koningsdag", 2024, 4, 27)
_reg("NL", None, "Koningsdag", 2025, 4, 26)   # 27 Apr Sun -> Sat 26 (nl_kingsday)
_reg("NL", None, "Hemelvaartsdag", *_mov(39))
_reg("NL", None, "Eerste Pinksterdag", *_mov(49))
_reg("NL", None, "Tweede Pinksterdag", *_mov(50))
_reg("NL", None, "Eerste Kerstdag", 2024, 12, 25)
_reg("NL", None, "Tweede Kerstdag", 2024, 12, 26)

# --- PL: statutory non-working days (Polish names); Wigilia from 2025 ---
_reg("PL", None, "Nowy Rok", 2024, 1, 1)
_reg("PL", None, "Święto Trzech Króli", 2024, 1, 6)
_reg("PL", None, "Niedziela Wielkanocna", *_mov(0))
_reg("PL", None, "Poniedziałek Wielkanocny", *_mov(1))
_reg("PL", None, "Święto Państwowe", 2024, 5, 1)
_reg("PL", None, "Święto Narodowe Trzeciego Maja", 2024, 5, 3)
_reg("PL", None, "Zielone Świątki", *_mov(49))
_reg("PL", None, "Dzień Bożego Ciała", *_mov(60))
_reg("PL", None, "Wniebowzięcie Najświętszej Marii Panny", 2024, 8, 15)
_reg("PL", None, "Uroczystość Wszystkich Świętych", 2024, 11, 1)
_reg("PL", None, "Narodowe Święto Niepodległości", 2024, 11, 11)
_reg("PL", None, "Wigilia Bożego Narodzenia", 2025, 12, 24)
_reg("PL", None, "Boże Narodzenie (pierwszy dzień)", 2024, 12, 25)
_reg("PL", None, "Boże Narodzenie (drugi dzień)", 2024, 12, 26)

# --- CZ: státní/ostatní svátky (Czech names) ---
_reg("CZ", None, "Nový rok", 2024, 1, 1)
_reg("CZ", None, "Velký pátek", *_mov(-2))
_reg("CZ", None, "Velikonoční pondělí", *_mov(1))
_reg("CZ", None, "Svátek práce", 2024, 5, 1)
_reg("CZ", None, "Den vítězství", 2024, 5, 8)
_reg("CZ", None, "Den slovanských věrozvěstů Cyrila a Metoděje", 2024, 7, 5)
_reg("CZ", None, "Den upálení mistra Jana Husa", 2024, 7, 6)
_reg("CZ", None, "Den české státnosti", 2024, 9, 28)
_reg("CZ", None, "Den vzniku samostatného československého státu", 2024, 10, 28)
_reg("CZ", None, "Den boje za svobodu a demokracii", 2024, 11, 17)
_reg("CZ", None, "Štědrý den", 2024, 12, 24)
_reg("CZ", None, "1. svátek vánoční", 2024, 12, 25)
_reg("CZ", None, "2. svátek vánoční", 2024, 12, 26)

# --- SK: štátne sviatky + dni pracovného pokoja (Slovak names) ---
_reg("SK", None, "Deň vzniku Slovenskej republiky", 2024, 1, 1)
_reg("SK", None, "Zjavenie Pána (Traja králi)", 2024, 1, 6)
_reg("SK", None, "Veľký piatok", *_mov(-2))
_reg("SK", None, "Veľkonočný pondelok", *_mov(1))
_reg("SK", None, "Sviatok práce", 2024, 5, 1)
_reg("SK", None, "Deň víťazstva nad fašizmom", 2024, 5, 8)
_reg("SK", None, "Sviatok svätého Cyrila a svätého Metoda", 2024, 7, 5)
_reg("SK", None, "Výročie Slovenského národného povstania", 2024, 8, 29)
_reg("SK", None, "Deň Ústavy Slovenskej republiky", 2023, 9, 1)  # work-free until 2023
_reg("SK", None, "Sedembolestná Panna Mária", 2024, 9, 15)
_reg("SK", None, "Sviatok Všetkých svätých", 2024, 11, 1)
_reg("SK", None, "Deň boja za slobodu a demokraciu", 2024, 11, 17)  # work-free until 2024
_reg("SK", None, "Štedrý deň", 2024, 12, 24)
_reg("SK", None, "Prvý sviatok vianočný", 2024, 12, 25)
_reg("SK", None, "Druhý sviatok vianočný", 2024, 12, 26)

# --- SE: allmänna helgdagar (Swedish names) ---
_reg("SE", None, "Nyårsdagen", 2024, 1, 1)
_reg("SE", None, "Trettondedag jul", 2024, 1, 6)
_reg("SE", None, "Långfredagen", *_mov(-2))
_reg("SE", None, "Påskdagen", *_mov(0))
_reg("SE", None, "Annandag påsk", *_mov(1))
_reg("SE", None, "Första maj", 2024, 5, 1)
_reg("SE", None, "Kristi himmelsfärdsdag", *_mov(39))
_reg("SE", None, "Pingstdagen", *_mov(49))
_reg("SE", None, "Sveriges nationaldag", 2024, 6, 6)
_reg("SE", None, "Midsommardagen", 2024, 6, 22)   # Sat on/before 26 Jun
_reg("SE", None, "Alla helgons dag", 2024, 11, 2)  # Sat on/before 6 Nov
_reg("SE", None, "Juldagen", 2024, 12, 25)
_reg("SE", None, "Annandag jul", 2024, 12, 26)

# --- DK: helligdage (Danish names); Store bededag abolished from 2024 ---
_reg("DK", None, "Nytårsdag", 2024, 1, 1)
_reg("DK", None, "Skærtorsdag", *_mov(-3))
_reg("DK", None, "Langfredag", *_mov(-2))
_reg("DK", None, "Påskedag", *_mov(0))
_reg("DK", None, "Anden påskedag", *_mov(1))
_reg("DK", None, "Store bededag", 2023, 5, 5)   # 4th Fri after Easter, until 2023
_reg("DK", None, "Kristi himmelfartsdag", *_mov(39))
_reg("DK", None, "Pinsedag", *_mov(49))
_reg("DK", None, "Anden pinsedag", *_mov(50))
_reg("DK", None, "Juledag", 2024, 12, 25)
_reg("DK", None, "Anden juledag", 2024, 12, 26)

# --- NO: helligdager (Norwegian names) ---
_reg("NO", None, "Første nyttårsdag", 2024, 1, 1)
_reg("NO", None, "Skjærtorsdag", *_mov(-3))
_reg("NO", None, "Langfredag", *_mov(-2))
_reg("NO", None, "Første påskedag", *_mov(0))
_reg("NO", None, "Andre påskedag", *_mov(1))
_reg("NO", None, "Arbeidernes dag", 2024, 5, 1)
_reg("NO", None, "Kristi himmelfartsdag", *_mov(39))
_reg("NO", None, "Grunnlovsdag", 2024, 5, 17)
_reg("NO", None, "Første pinsedag", *_mov(49))
_reg("NO", None, "Andre pinsedag", *_mov(50))
_reg("NO", None, "Første juledag", 2024, 12, 25)
_reg("NO", None, "Andre juledag", 2024, 12, 26)

# --- FI: official holidays (Finnish / Swedish names) ---
_reg("FI", None, "Uudenvuodenpäivä / Nyårsdagen", 2024, 1, 1)
_reg("FI", None, "Loppiainen / Trettondedag jul", 2024, 1, 6)
_reg("FI", None, "Pitkäperjantai / Långfredagen", *_mov(-2))
_reg("FI", None, "Pääsiäispäivä / Påskdagen", *_mov(0))
_reg("FI", None, "Toinen pääsiäispäivä / Annandag påsk", *_mov(1))
_reg("FI", None, "Vappu / Första maj", 2024, 5, 1)
_reg("FI", None, "Helatorstai / Kristi himmelsfärdsdag", *_mov(39))
_reg("FI", None, "Helluntaipäivä / Pingst", *_mov(49))
_reg("FI", None, "Juhannusaatto / Midsommarafton", 2024, 6, 21)  # Fri on/before 25 Jun
_reg("FI", None, "Juhannuspäivä / Midsommardagen", 2024, 6, 22)  # Sat on/before 26 Jun
_reg("FI", None, "Pyhäinpäivä / Alla helgons dag", 2024, 11, 2)  # Sat on/before 6 Nov
_reg("FI", None, "Itsenäisyyspäivä / Självständighetsdagen", 2024, 12, 6)
_reg("FI", None, "Jouluaatto / Julafton", 2024, 12, 24)
_reg("FI", None, "Joulupäivä / Juldagen", 2024, 12, 25)
_reg("FI", None, "Tapaninpäivä / Annandag jul", 2024, 12, 26)

@pytest.mark.parametrize("country,subdiv,name,year,month,day", [
    (c, s, n, y, m, d)
    for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c in _T2A
    for (y, m, d) in ymds
])
def test_t2a_gold(country, subdiv, name, year, month, day):
    got = _dateset_for(country, year, subdiv=subdiv)
    assert AstroDate(year, month, day) in got.get((name, subdiv), set()), (
        f"{country}/{subdiv}/{name!r} {year}: expected "
        f"{year}-{month:02d}-{day:02d}, got "
        f"{sorted(got.get((name, subdiv), set()))}")


# ==========================================================================
# Structural enforcement: every rule in every holiday_data/*.tab needs a gold.
# ==========================================================================
def _every_tab_rule_key():
    """(country, subdiv, name) for every rule row in every shipped .tab file."""
    keys = []
    for fn in sorted(os.listdir(_DATA_DIR)):
        if not fn.endswith(".tab"):
            continue
        cal = load_calendar(os.path.join(_DATA_DIR, fn))
        for rule in cal.rules:
            keys.append((cal.jurisdiction.upper(), rule.subdiv, rule.name))
    return keys


@pytest.mark.parametrize("country,subdiv,name", _every_tab_rule_key())
def test_every_tab_rule_has_a_gold(country, subdiv, name):
    """Enforces only for jurisdictions with a holiday_data/*.tab file present
    in THIS checkout -- countries whose data+golds haven't merged yet simply
    don't appear in ``_every_tab_rule_key()``, so parallel branches (adding
    e.g. de.tab) never conflict with each other here."""
    assert (country, subdiv, name) in HOLIDAY_GOLDS, (
        f"no gold registered for {country}/{subdiv}/{name!r}; "
        f"add one to HOLIDAY_GOLDS (see this module's docstring)")
