"""Standing-rule backfill: every holiday_data/*.tab rule gets its own gold.

Convention for parallel agents (UK/DE/FR/ES/BR/CA/AU/IN/CN/JP/TR/IL golds land
on other branches and merge later)
--------------------------------------------------------------------------
``HOLIDAY_GOLDS`` is a module-level ``dict`` keyed ``(country, subdiv, name)``
-> a set of ``(year, month, day)`` triples that ``holidays_for`` must produce
for that rule (a rule may resolve to more than one date in a year, e.g. a
``calendar_date`` rule near a lunar-year boundary, or none, per calendar
range rules -- register every year you assert). ``country`` is the upper-case
jurisdiction code (``"PT"``), ``subdiv`` is ``None`` for a jurisdiction-wide
rule or the exact subdivision code from the ``.tab`` file, and ``name`` is the
rule's exact ``name`` column. Register your country's golds into this same
dict (import it from this module and update it at import time, the same way
the PT/US/SA sections below do) so ``test_every_tab_rule_has_a_gold`` -- the
structural enforcement test -- can find them. That test only enforces
jurisdictions for which a ``holiday_data/<cc>.tab`` file is actually present
in this checkout, so an unmerged branch adding e.g. ``de.tab`` + its golds in
the same PR never conflicts with another branch's unmerged ``fr.tab``.

Sourcing discipline
--------------------
* US: every federal entry, including both observed-shift variants, dated from
  the OPM/Wikipedia list already cited in the ``.tab`` header and mirrored at
  ``papers/holidays/us_federal_holidays_wikipedia.html``; the shift itself
  follows 5 U.S.C. 6103 (Sat -> preceding Fri, Sun -> following Mon).
* SA: every entry. The two fixed (Gregorian) days come straight from the
  cited Wikipedia page. The six Islamic days are NOT taken from the engine's
  own ``CalendarDateRule`` conversion -- they are independently re-derived
  here from the raw ``jdn_start`` column of
  ``chronologia/calendar_data/umm_al_qura.tab`` (AH 1445 Shawwal/Dhu
  al-Hijjah) through a standalone Fliegel-van Flandern JDN->Gregorian
  formula that imports nothing from ``chronologia`` -- so this file, not the
  engine, is the independent witness. The result (Eid al-Fitr 2024-04-10,
  Eid al-Adha 2024-06-16) also matches the publicly known 2024 Hijri
  calendar.
* PT national + regional: hand golds, movable ones derived in-test via
  ``easter(2024)`` + the documented Codigo do Trabalho offset.
* PT municipal (fixed, ~224 entries -- the bulk): NOT hand-typed. Golds are
  generated by parsing the cited seed
  ``papers/holidays/feriados.tsv`` (date + municipality names) and
  ``papers/holidays/municipios_portugal.csv`` (municipality name -> ISO
  subdivision code), then cross-checked one-for-one against every
  ``fixed ... municipal`` row of ``pt.tab``. This is source-vs-engine: the
  expected date comes from the TSV text, not from the ``.tab`` file's own
  ``args`` column.
* PT municipal (movable, ~73 entries): golds are generated by parsing
  ``papers/holidays/feriados_moveis.tsv``'s Portuguese date phrases
  ("Segunda-feira apos a Pascoa", "Segunda-feira apos o segundo Domingo de
  Julho", ...) through a small hand-written phrase -> rule mapping table
  (mirrored from the documented conversions in that file, not copied from
  ``pt.tab``), evaluated against ``easter(2024)`` / the RRULE nth-weekday
  engine, and cross-checked against ``pt.tab``'s ``easter``/``nth_weekday``
  rows. Two phrase-mapping bugs were caught and fixed against this
  independent derivation while building this file (see "Disagreements
  found" below) -- both turned out to be errors in the phrase table, not in
  ``pt.tab``, once resolved carefully; see the module docstring further
  below for the one thing that *did* warrant a closer look.

Disagreements found while building this backfill
--------------------------------------------------------------------------
None that survive: two apparent PT movable-municipal mismatches surfaced
during authoring (Ponta Delgada's "Senhor Santo Cristo dos Milagres" and
Vieira do Minho's "Feira da Ladra") but both traced back to this file's own
first-draft phrase table -- "Quinta Segunda-feira" is the *fifth* Monday
after Easter (Portuguese ordinal quinta = 5th, not 4th), and "the Monday
after the first Saturday of October" is two days after that Saturday, not
one. With the phrase table corrected, all 224 fixed + 73 movable PT
municipal rows agree with the source TSVs, and the source TSVs' own
municipality-name spellings needed a small alias table (Madeira/Acores
disambiguating suffixes, accents, "Praia da Vitoria" -> "Vila da Praia da
Vitoria") to line up with ``municipios_portugal.csv``'s codes -- listed
inline below, not silently dropped.
"""
import csv
import os
import re
from datetime import timedelta

import pytest

from chronologia import AstroDate, holidays_for, load_calendar
from chronologia.civil_holidays import _DATA_DIR
from chronologia.computus import easter
from chronologia.recurrence import nth_weekday_of_month, occurrences

_PAPERS = os.path.expanduser("~/AgentWorkspaces/papers/holidays")

#: The shared registry. Keys: (country, subdiv, name). Values: set of
#: (year, month, day) triples ``holidays_for`` must produce.
HOLIDAY_GOLDS: dict = {}


def _reg(country, subdiv, name, *ymd):
    HOLIDAY_GOLDS.setdefault((country, subdiv, name), set()).add(ymd)


def _dates_for(country, year, subdiv=None):
    return {(h.name, h.subdiv): h.date for h in holidays_for(country, year, subdiv)}


# ==========================================================================
# US -- federal holidays, 2024 + the two observed-shift-exercising years.
# ==========================================================================
_US_2024 = {
    "New Year's Day": (1, 1),
    "Birthday of Martin Luther King, Jr.": (1, 15),
    "Washington's Birthday": (2, 19),
    "Memorial Day": (5, 27),
    "Juneteenth National Independence Day": (6, 19),
    "Independence Day": (7, 4),
    "Labor Day": (9, 2),
    "Columbus Day": (10, 14),
    "Veterans Day": (11, 11),
    "Thanksgiving Day": (11, 28),
    "Christmas Day": (12, 25),
}
for _name, (_m, _d) in _US_2024.items():
    _reg("US", None, _name, 2024, _m, _d)

# Observed-shift exercising years (5 U.S.C. 6103): July 4 2021 fell on a
# Sunday (observed Monday July 5); Dec 25 2022 fell on a Sunday (observed
# Monday Dec 26).
_reg("US", None, "Independence Day", 2021, 7, 5)
_reg("US", None, "Christmas Day", 2022, 12, 26)


@pytest.mark.parametrize("name,year,month,day", [
    (n, y, m, d) for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c == "US" for (y, m, d) in ymds
])
def test_us_gold(name, year, month, day):
    got = _dates_for("US", year)
    assert got[(name, None)] == AstroDate(year, month, day)


# ==========================================================================
# SA -- fixed Gregorian days (Wikipedia) + Islamic days independently
# re-derived from the raw umm_al_qura.tab JDN column.
# ==========================================================================
_reg("SA", None, "Founding Day", 2024, 2, 22)
_reg("SA", None, "National Day", 2024, 9, 23)


def _jdn_to_gregorian(jdn: int):
    """Fliegel & van Flandern (1968) JDN->Gregorian, standalone (no chronologia import)."""
    ell = jdn + 68569
    n = (4 * ell) // 146097
    ell = ell - (146097 * n + 3) // 4
    i = (4000 * (ell + 1)) // 1461001
    ell = ell - (1461 * i) // 4 + 31
    j = (80 * ell) // 2447
    day = ell - (2447 * j) // 80
    ell2 = j // 11
    month = j + 2 - 12 * ell2
    year = 100 * (n - 49) + i + ell2
    return year, month, day


def _umm_al_qura_month_start(ah_year: int, ah_month: int) -> int:
    """Read ``jdn_start`` straight out of the raw calendar_data table (no
    calendars.py machinery -- an independent re-read of the same published
    source table cited in ``sa.tab``'s header)."""
    path = os.path.join(os.path.dirname(_DATA_DIR), "calendar_data", "umm_al_qura.tab")
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            y, m, leap, jdn = line.split()
            if int(y) == ah_year and int(m) == ah_month:
                return int(jdn)
    raise LookupError((ah_year, ah_month))


# 1 Shawwal AH 1445 = Eid al-Fitr; 10 Dhu al-Hijjah AH 1445 = Eid al-Adha.
_shawwal_start = _umm_al_qura_month_start(1445, 10)
_dhulhijjah_start = _umm_al_qura_month_start(1445, 12)
for _i, _name in enumerate(("Eid al-Fitr", "Eid al-Fitr Holiday", "Eid al-Fitr Holiday")):
    _y, _m, _d = _jdn_to_gregorian(_shawwal_start + _i)
    _reg("SA", None, _name, _y, _m, _d)
for _i, _name in enumerate((
        "Arafah Day", "Eid al-Adha", "Eid al-Adha Holiday",
        "Eid al-Adha Holiday", "Eid al-Adha Holiday"), start=8):
    _y, _m, _d = _jdn_to_gregorian(_dhulhijjah_start + _i)
    _reg("SA", None, _name, _y, _m, _d)

# The Eid holidays repeat identical names ("Eid al-Fitr Holiday" twice, "Eid
# al-Adha Holiday" three times); the engine yields them in date order, so
# golds are asserted positionally against the sorted, deduped output.
_SA_ISLAMIC_ORDER_2024 = [
    "Eid al-Fitr", "Eid al-Fitr Holiday", "Eid al-Fitr Holiday",
    "Arafah Day", "Eid al-Adha", "Eid al-Adha Holiday",
    "Eid al-Adha Holiday", "Eid al-Adha Holiday",
]
_SA_ISLAMIC_DATES_2024 = sorted(
    _jdn_to_gregorian(_shawwal_start + i) for i in range(3)
) + sorted(_jdn_to_gregorian(_dhulhijjah_start + i) for i in range(8, 13))


def test_sa_fixed_golds_2024():
    got = _dates_for("SA", 2024)
    assert got[("Founding Day", None)] == AstroDate(2024, 2, 22)
    assert got[("National Day", None)] == AstroDate(2024, 9, 23)


def test_sa_islamic_golds_2024_independent_jdn_rederivation():
    got = sorted(h.date for h in holidays_for("SA", 2024)
                 if "religious" in h.categories)
    expect = [AstroDate(y, m, d) for (y, m, d) in _SA_ISLAMIC_DATES_2024]
    assert got == expect
    assert len(got) == 8
    # Sanity: matches the well-known public 2024 Hijri calendar.
    assert AstroDate(2024, 4, 10) in got  # Eid al-Fitr
    assert AstroDate(2024, 6, 16) in got  # Eid al-Adha


# ==========================================================================
# PT -- national + regional (hand golds, movable derived via easter(2024)).
# ==========================================================================
_E2024 = easter(2024, "gregorian")

_reg("PT", None, "Ano Novo", 2024, 1, 1)
_reg("PT", None, "Sexta-feira Santa", *(2024, (_E2024 + timedelta(days=-2)).month,
                                        (_E2024 + timedelta(days=-2)).day))
_reg("PT", None, "Domingo de Pascoa", 2024, _E2024.month, _E2024.day)
_reg("PT", None, "Dia da Liberdade", 2024, 4, 25)
_reg("PT", None, "Dia do Trabalhador", 2024, 5, 1)
_reg("PT", None, "Corpo de Deus", *(2024, (_E2024 + timedelta(days=60)).month,
                                    (_E2024 + timedelta(days=60)).day))
_reg("PT", None, "Dia de Portugal", 2024, 6, 10)
_reg("PT", None, "Assuncao de Nossa Senhora", 2024, 8, 15)
_reg("PT", None, "Implantacao da Republica", 2024, 10, 5)
_reg("PT", None, "Dia de Todos os Santos", 2024, 11, 1)
_reg("PT", None, "Restauracao da Independencia", 2024, 12, 1)
_reg("PT", None, "Imaculada Conceicao", 2024, 12, 8)
_reg("PT", None, "Natal", 2024, 12, 25)
_reg("PT", None, "Carnaval", *(2024, (_E2024 + timedelta(days=-47)).month,
                               (_E2024 + timedelta(days=-47)).day))
_reg("PT", "PT-30", "Dia da Regiao Autonoma da Madeira", 2024, 7, 1)
_reg("PT", "PT-20", "Dia da Regiao Autonoma dos Acores",
     *(2024, (_E2024 + timedelta(days=50)).month, (_E2024 + timedelta(days=50)).day))


@pytest.mark.parametrize("subdiv,name,year,month,day", [
    (s, n, y, m, d) for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c == "PT" and s in (None, "PT-30", "PT-20") for (y, m, d) in ymds
])
def test_pt_national_and_regional_gold(subdiv, name, year, month, day):
    got = _dates_for("PT", year, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(year, month, day)


# ==========================================================================
# PT municipal -- fixed (source: feriados.tsv + municipios_portugal.csv).
# ==========================================================================
_MONTHS_PT = {
    "Janeiro": 1, "Fevereiro": 2, "Marco": 3, "Março": 3, "Abril": 4, "Maio": 5,
    "Junho": 6, "Julho": 7, "Agosto": 8, "Setembro": 9, "Outubro": 10,
    "Novembro": 11, "Dezembro": 12,
}

#: Municipality-name aliases needed to reconcile feriados.tsv/feriados_moveis.tsv
#: spellings with municipios_portugal.csv's codes: Madeira/Acores disambiguating
#: suffixes the seed applies but the code list doesn't (or spells differently),
#: an accent difference, and one differently-ordered official name.
_MUNI_ALIASES = {
    "Santa Cruz (Madeira)": "Santa Cruz",
    "Calheta (Madeira)": "Calheta (Funchal)",
    # pt.tab's PT-LGA is the Sao Miguel (Acores) Lagoa, matching
    # municipios_portugal.csv's bare "Lagoa" -- NOT the "Lagoa (Ponta
    # Delgada)" row, which pt.tab carries no rule for at all.
    "Lagoa (Acores)": "Lagoa",
    "Santana (Madeira)": "Santana",
    "Praia da Vitoria": "Vila da Praia da Vitoria",
    "Vila Nova do Corvo": "Corvo",
    "Castanheira de Pera": "Castanheira de Pera",  # accent handled by _fold
    "Nordeste (Acores)": "Nordeste",
    "Silves (Portugal)": "Silves",
    "Meda": "Meda",  # accent handled by _fold
    "Povoacao (Acores)": "Povoacao",
    "Idanha-A-Nova": "Idanha-a-Nova",
}
#: Municipalities named in the seed rows that are not distinct concelhos in
#: municipios_portugal.csv (freguesias of an already-listed municipality) --
#: dropped, not silently mismatched, because pt.tab carries no separate rule
#: for them either.
_MUNI_NOT_A_CONCELHO = {"Quarteira"}


def _fold(name: str) -> str:
    """ASCII-fold (via Unicode NFKD decomposition) + normalize whitespace,
    for robust municipality-name lookup regardless of accents."""
    import unicodedata
    decomposed = unicodedata.normalize("NFKD", name)
    stripped = "".join(c for c in decomposed if not unicodedata.combining(c))
    return " ".join(stripped.split())


#: Alias lookup keyed by folded (accent/whitespace-normalized) name, so a
#: source string with or without accents resolves the same way.
_MUNI_ALIASES_FOLDED = {_fold(k): v for k, v in _MUNI_ALIASES.items()}


def _load_municipio_codes() -> dict:
    path = os.path.join(_PAPERS, "municipios_portugal.csv")
    codes = {}
    with open(path, encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            codes[_fold(row["Municipio"].strip())] = "PT-" + row["Codigo"].strip()
    return codes


def _resolve_muni_code(name: str, codes: dict):
    folded = _fold(name)
    name = _MUNI_ALIASES_FOLDED.get(folded, name)
    return codes.get(_fold(name))


def _split_municipalities(field: str):
    """The seed's municipio column is a comma/'e'-joined list, sometimes
    trailing into free-text prose after a period -- keep only the list."""
    field = field.split(".")[0].replace(" e ", ", ")
    return [n.strip() for n in field.split(",") if n.strip()]


def _load_pt_tab_municipal(kinds):
    """Every ``kind in kinds`` municipal row of pt.tab, as a list (a subdiv
    may carry more than one rule, e.g. PT-LGA has both a fixed "Criacao do
    municipio" AND a fixed "Nossa Senhora da Luz" -- a dict keyed on subdiv
    alone would silently drop one)."""
    out = []
    with open(os.path.join(_DATA_DIR, "pt.tab"), encoding="utf-8") as fh:
        for line in fh:
            if line.lstrip().startswith("#") or not line.strip():
                continue
            cols = [c.strip() for c in line.split("|")]
            if "municipal" not in cols[3] or cols[0] not in kinds:
                continue
            out.append((cols[4], cols[0], cols[2], cols[1]))  # subdiv,kind,args,name
    return out


def _pt_fixed_municipal_source_golds():
    """Parse feriados.tsv -> {(subdiv, name): (month, day)} (source-derived,
    not read from pt.tab)."""
    codes = _load_municipio_codes()
    out = {}
    path = os.path.join(_PAPERS, "feriados.tsv")
    with open(path, encoding="utf-8") as fh:
        next(fh)
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            data, feriado, muni_field = parts[0], parts[1].strip(), parts[2]
            m = re.match(r"\s*(\d+)\s*de\s*(\w+)", data.strip())
            day, month = int(m.group(1)), _MONTHS_PT[m.group(2)]
            for n in _split_municipalities(muni_field):
                if n in _MUNI_NOT_A_CONCELHO:
                    continue
                code = _resolve_muni_code(n, codes)
                # feriados.tsv is a superset of pt.tab's municipal seed: a
                # handful of its names (Valenca do Minho, Vizela, Odivelas,
                # Trofa, bare "Calheta") aren't in municipios_portugal.csv
                # and have no corresponding pt.tab row either -- harmless,
                # skip rather than fail; coverage is enforced the other way
                # round below (every pt.tab row must resolve).
                if code is None:
                    continue
                out[(code, feriado)] = (month, day)
    return out


_PT_MUNICIPAL_FIXED_SOURCE = _pt_fixed_municipal_source_golds()
#: [(subdiv, month, day, name)] -- ``_load_pt_tab_municipal`` returns raw
#: (subdiv, kind, args, name); "fixed" args are "<month> <day>", parsed here.
_PT_MUNICIPAL_FIXED_TAB = [
    (subdiv, int(args.split()[0]), int(args.split()[1]), name)
    for subdiv, kind, args, name in _load_pt_tab_municipal({"fixed"})
]

for _subdiv, _m, _d, _n in _PT_MUNICIPAL_FIXED_TAB:
    assert (_subdiv, _n) in _PT_MUNICIPAL_FIXED_SOURCE, (
        f"{_subdiv} ({_n!r}) has no matching feriados.tsv row")
    _reg("PT", _subdiv, _n, 2024, _m, _d)


@pytest.mark.parametrize("subdiv,name,month,day", sorted(
    (s, n, m, d) for s, m, d, n in _PT_MUNICIPAL_FIXED_TAB))
def test_pt_municipal_fixed_gold_matches_source(subdiv, name, month, day):
    """Source-vs-engine: the feriados.tsv-derived (month, day) must equal
    both the engine's resolved 2024 date AND the .tab file's own args (a
    disagreement anywhere here is a BUG REPORT item, not silently aligned)."""
    src_month, src_day = _PT_MUNICIPAL_FIXED_SOURCE[(subdiv, name)]
    assert (src_month, src_day) == (month, day)
    got = _dates_for("PT", 2024, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(2024, month, day)


def test_pt_municipal_fixed_gold_count():
    assert len(_PT_MUNICIPAL_FIXED_TAB) == 224


# ==========================================================================
# PT municipal -- movable (source: feriados_moveis.tsv phrase table).
# ==========================================================================
def _nth_weekday_2024(month, n, weekday, post_offset=0):
    rec = nth_weekday_of_month(n, weekday, month=month)
    got = list(occurrences(rec, AstroDate(2024, 1, 1), until=AstroDate(2024, 12, 31)))
    return got[0].start + timedelta(days=post_offset)


#: Mirrors the documented conversions in feriados_moveis.tsv, NOT copied from
#: pt.tab -- see the module docstring for the two mapping bugs this caught
#: (and fixed here) before the two files agreed.
_MOVABLE_PHRASE_RULES = [
    (r"^Segunda-feira apos a Pascoa$", lambda: _E2024 + timedelta(days=1)),
    (r"^Segunda Segunda-feira apos a Pascoa", lambda: _E2024 + timedelta(days=8)),
    (r"^Terceira Segunda-feira apos a Pascoa", lambda: _E2024 + timedelta(days=15)),
    (r"^Terca-feira que segue o primeiro domingo depois da Pascoa",
     lambda: _E2024 + timedelta(days=9)),
    # "Quinta" = ordinal FIFTH (not fourth) Monday after Easter -- there is no
    # "Quarta Segunda-feira" row in the source, confirmed against pt.tab's 29.
    (r"^Quinta Segunda-feira apos a Pascoa", lambda: _E2024 + timedelta(days=29)),
    (r"^Sexta Quinta-feira apos o Domingo de Pascoa", lambda: _E2024 + timedelta(days=39)),
    (r"^Segunda-feira apos o Domingo de Pentecostes", lambda: _E2024 + timedelta(days=50)),
    (r"^Terca-Feira apos o Domingo de Pentecostes", lambda: _E2024 + timedelta(days=51)),
    (r"^Sexta-feira a seguir ao Dia de Corpo de Deus", lambda: _E2024 + timedelta(days=61)),
    (r"^Segunda-feira apos o segundo Domingo de Julho", lambda: _nth_weekday_2024(7, 2, 6, 1)),
    (r"^Segunda-feira apos o terceiro Domingo de Julho", lambda: _nth_weekday_2024(7, 3, 6, 1)),
    (r"^Segunda-feira apos o ultimo Domingo de Julho", lambda: _nth_weekday_2024(7, -1, 6, 1)),
    (r"^Segunda-feira apos o primeiro Domingo de Agosto", lambda: _nth_weekday_2024(8, 1, 6, 1)),
    (r"^Segunda-feira apos o segundo Domingo de Agosto", lambda: _nth_weekday_2024(8, 2, 6, 1)),
    (r"^Segunda-feira apos o terceiro Domingo de Agosto", lambda: _nth_weekday_2024(8, 3, 6, 1)),
    (r"^Segunda-feira apos o quarto Domingo de Agosto", lambda: _nth_weekday_2024(8, 4, 6, 1)),
    (r"^Segunda Sexta-feira de Setembro", lambda: _nth_weekday_2024(9, 2, 4)),
    (r"^Terca-feira apos o segundo Domingo de Setembro", lambda: _nth_weekday_2024(9, 2, 6, 2)),
    (r"^Segunda-feira apos o primeiro Domingo de Outubro", lambda: _nth_weekday_2024(10, 1, 6, 1)),
    # "the Monday AFTER that Saturday", i.e. +2 days from the Saturday, not +1.
    (r"^Segunda-feira apos o primeiro Sabado de Outubro", lambda: _nth_weekday_2024(10, 1, 5, 2)),
]


def _pt_movable_municipal_source_golds():
    """Parse feriados_moveis.tsv -> {subdiv: (AstroDate, name)}."""
    codes = _load_municipio_codes()
    out = {}
    path = os.path.join(_PAPERS, "feriados_moveis.tsv")
    with open(path, encoding="utf-8") as fh:
        next(fh)
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            data, feriado, muni_field = parts[0], parts[1].strip(), parts[2]
            data_folded = _fold(data.strip())
            rule_fn = None
            for pat, fn in _MOVABLE_PHRASE_RULES:
                if re.match(_fold(pat), data_folded):
                    rule_fn = fn
                    break
            assert rule_fn is not None, f"unrecognised feriados_moveis.tsv phrase: {data!r}"
            date = rule_fn()
            for n in _split_municipalities(muni_field):
                if n in _MUNI_NOT_A_CONCELHO:
                    continue
                code = _resolve_muni_code(n, codes)
                if code is None:
                    continue
                out[code] = (date, feriado)
    return out


_PT_MUNICIPAL_MOVABLE_SOURCE = _pt_movable_municipal_source_golds()
#: [(subdiv, kind, args, name)] -- no subdiv carries two movable rules (checked),
#: but kept as a list for the same reason as the fixed table above.
_PT_MUNICIPAL_MOVABLE_TAB = _load_pt_tab_municipal({"easter", "nth_weekday"})

for _subdiv, _kind, _args, _n in _PT_MUNICIPAL_MOVABLE_TAB:
    assert _subdiv in _PT_MUNICIPAL_MOVABLE_SOURCE, (
        f"{_subdiv} ({_n!r}) has no matching feriados_moveis.tsv row")
    _date, _ = _PT_MUNICIPAL_MOVABLE_SOURCE[_subdiv]
    _reg("PT", _subdiv, _n, 2024, _date.month, _date.day)


@pytest.mark.parametrize("subdiv,kind,args,name", sorted(_PT_MUNICIPAL_MOVABLE_TAB))
def test_pt_municipal_movable_gold_matches_source(subdiv, kind, args, name):
    """Source-vs-engine: the feriados_moveis.tsv phrase-derived date must
    equal the engine's resolved 2024 date. Disagreements are BUG REPORT
    items, not silently aligned (see the two caught during authoring, both
    traced to this file's phrase table rather than pt.tab -- module docstring)."""
    src_date, _ = _PT_MUNICIPAL_MOVABLE_SOURCE[subdiv]
    got = _dates_for("PT", 2024, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(src_date.year, src_date.month, src_date.day)


def test_pt_municipal_movable_gold_count():
    assert len(_PT_MUNICIPAL_MOVABLE_TAB) == 73


def test_pt_municipal_gold_total():
    assert len(_PT_MUNICIPAL_FIXED_TAB) + len(_PT_MUNICIPAL_MOVABLE_TAB) == 297


# ==========================================================================
# Wave 1a: GB, DE, FR, ES, BR, CA (national + subdivisions).
# Golds hand-derived from each country's cited primary source (see the .tab
# header + papers/holidays/INDEX.md); movable days re-derived here via
# easter(2024) + the documented offset (``_mov``), never read from the engine.
# Full sourcing, subdivision scope decisions, and the documented reference
# differential disagreements live in the per-country test modules
# (test_holidays_<cc>.py), which own the differential + behavioural assertions.
# ==========================================================================
def _mov(offset):
    """(2024, month, day) for a day at ``easter(2024) + offset`` (independent)."""
    d = _E2024 + timedelta(days=offset)
    return (2024, d.month, d.day)


# --- GB: UK bank holidays (source: gov.uk/bank-holidays) ---
_reg("GB", None, "New Year's Day", 2024, 1, 1)
_reg("GB", None, "Good Friday", *_mov(-2))
_reg("GB", None, "Early May Bank Holiday", 2024, 5, 6)   # 1st Monday of May
_reg("GB", None, "Spring Bank Holiday", 2024, 5, 27)     # last Monday of May
_reg("GB", None, "Christmas Day", 2024, 12, 25)
_reg("GB", None, "Boxing Day", 2024, 12, 26)
_reg("GB", "GB-EAW", "Easter Monday", *_mov(1))
_reg("GB", "GB-EAW", "Summer Bank Holiday", 2024, 8, 26)  # last Monday of Aug
_reg("GB", "GB-SCT", "2nd January", 2024, 1, 2)
_reg("GB", "GB-SCT", "Summer Bank Holiday", 2024, 8, 5)   # 1st Monday of Aug
_reg("GB", "GB-SCT", "St Andrew's Day", 2024, 11, 30)
_reg("GB", "GB-NIR", "St Patrick's Day", 2024, 3, 17)
_reg("GB", "GB-NIR", "Easter Monday", *_mov(1))
_reg("GB", "GB-NIR", "Battle of the Boyne", 2024, 7, 12)
_reg("GB", "GB-NIR", "Summer Bank Holiday", 2024, 8, 26)  # last Monday of Aug

# --- DE: national nine + all 16 Länder (source: Land Feiertagsgesetze) ---
_reg("DE", None, "Neujahr", 2024, 1, 1)
_reg("DE", None, "Karfreitag", *_mov(-2))
_reg("DE", None, "Ostermontag", *_mov(1))
_reg("DE", None, "Erster Mai", 2024, 5, 1)
_reg("DE", None, "Christi Himmelfahrt", *_mov(39))
_reg("DE", None, "Pfingstmontag", *_mov(50))
_reg("DE", None, "Tag der Deutschen Einheit", 2024, 10, 3)
_reg("DE", None, "Erster Weihnachtstag", 2024, 12, 25)
_reg("DE", None, "Zweiter Weihnachtstag", 2024, 12, 26)
for _s in ("DE-BW", "DE-BY", "DE-ST"):
    _reg("DE", _s, "Heilige Drei Könige", 2024, 1, 6)
for _s in ("DE-BE", "DE-MV"):
    _reg("DE", _s, "Internationaler Frauentag", 2024, 3, 8)
_reg("DE", "DE-BB", "Ostersonntag", *_mov(0))
_reg("DE", "DE-BB", "Pfingstsonntag", *_mov(49))
for _s in ("DE-BW", "DE-BY", "DE-HE", "DE-NW", "DE-RP", "DE-SL"):
    _reg("DE", _s, "Fronleichnam", *_mov(60))
_reg("DE", "DE-SL", "Mariä Himmelfahrt", 2024, 8, 15)
_reg("DE", "DE-TH", "Weltkindertag", 2024, 9, 20)
for _s in ("DE-BB", "DE-HB", "DE-HH", "DE-MV", "DE-NI", "DE-SN", "DE-ST",
           "DE-SH", "DE-TH"):
    _reg("DE", _s, "Reformationstag", 2024, 10, 31)
for _s in ("DE-BW", "DE-BY", "DE-NW", "DE-RP", "DE-SL"):
    _reg("DE", _s, "Allerheiligen", 2024, 11, 1)
_reg("DE", "DE-SN", "Buß- und Bettag", 2024, 11, 20)  # Wed on/before 22 Nov

# --- FR: 11 national + Alsace-Moselle extras (source: service-public.fr) ---
_reg("FR", None, "Jour de l'an", 2024, 1, 1)
_reg("FR", None, "Lundi de Pâques", *_mov(1))
_reg("FR", None, "Fête du Travail", 2024, 5, 1)
_reg("FR", None, "Fête de la Victoire", 2024, 5, 8)
_reg("FR", None, "Ascension", *_mov(39))
_reg("FR", None, "Lundi de Pentecôte", *_mov(50))
_reg("FR", None, "Fête nationale", 2024, 7, 14)
_reg("FR", None, "Assomption", 2024, 8, 15)
_reg("FR", None, "Toussaint", 2024, 11, 1)
_reg("FR", None, "Armistice 1918", 2024, 11, 11)
_reg("FR", None, "Noël", 2024, 12, 25)
for _s in ("FR-57", "FR-6AE"):
    _reg("FR", _s, "Vendredi saint", *_mov(-2))
    _reg("FR", _s, "Saint Étienne", 2024, 12, 26)

# --- ES: national fixed set only (source: Estatuto de los Trabajadores) ---
_reg("ES", None, "Año Nuevo", 2024, 1, 1)
_reg("ES", None, "Epifanía del Señor", 2024, 1, 6)
_reg("ES", None, "Viernes Santo", *_mov(-2))
_reg("ES", None, "Fiesta del Trabajo", 2024, 5, 1)
_reg("ES", None, "Asunción de la Virgen", 2024, 8, 15)
_reg("ES", None, "Fiesta Nacional de España", 2024, 10, 12)
_reg("ES", None, "Todos los Santos", 2024, 11, 1)
_reg("ES", None, "Día de la Constitución Española", 2024, 12, 6)
_reg("ES", None, "Inmaculada Concepción", 2024, 12, 8)
_reg("ES", None, "Natividad del Señor", 2024, 12, 25)

# --- BR: national feriados + facultative Carnaval/Corpus (source: Planalto) ---
_reg("BR", None, "Confraternização Universal", 2024, 1, 1)
_reg("BR", None, "Sexta-feira Santa", *_mov(-2))
_reg("BR", None, "Tiradentes", 2024, 4, 21)
_reg("BR", None, "Dia do Trabalhador", 2024, 5, 1)
_reg("BR", None, "Independência do Brasil", 2024, 9, 7)
_reg("BR", None, "Nossa Senhora Aparecida", 2024, 10, 12)
_reg("BR", None, "Finados", 2024, 11, 2)
_reg("BR", None, "Proclamação da República", 2024, 11, 15)
_reg("BR", None, "Dia Nacional de Zumbi e da Consciência Negra", 2024, 11, 20)
_reg("BR", None, "Natal", 2024, 12, 25)
_reg("BR", None, "Carnaval", *_mov(-47))
_reg("BR", None, "Corpus Christi", *_mov(60))
_reg("BR", "BR-SP", "Revolução Constitucionalista", 2024, 7, 9)
_reg("BR", "BR-RJ", "São Jorge", 2024, 4, 23)

# --- CA: federal + compact provincial sample (source: Holidays Act + provinces) ---
_reg("CA", None, "New Year's Day", 2024, 1, 1)
_reg("CA", None, "Good Friday", *_mov(-2))
_reg("CA", None, "Canada Day", 2024, 7, 1)
_reg("CA", None, "Labour Day", 2024, 9, 2)               # 1st Monday of Sept
_reg("CA", None, "Christmas Day", 2024, 12, 25)
_reg("CA", "CA-ON", "Family Day", 2024, 2, 19)           # 3rd Monday of Feb
_reg("CA", "CA-ON", "Victoria Day", 2024, 5, 20)         # Monday preceding 25 May
_reg("CA", "CA-ON", "Thanksgiving Day", 2024, 10, 14)    # 2nd Monday of Oct
_reg("CA", "CA-ON", "Boxing Day", 2024, 12, 26)
_reg("CA", "CA-QC", "National Patriots' Day", 2024, 5, 20)
_reg("CA", "CA-QC", "Saint-Jean-Baptiste", 2024, 6, 24)
_reg("CA", "CA-QC", "Thanksgiving Day", 2024, 10, 14)
_reg("CA", "CA-BC", "Family Day", 2024, 2, 19)
_reg("CA", "CA-BC", "Victoria Day", 2024, 5, 20)
_reg("CA", "CA-BC", "British Columbia Day", 2024, 8, 5)  # 1st Monday of Aug
_reg("CA", "CA-BC", "National Day for Truth and Reconciliation", 2024, 9, 30)
_reg("CA", "CA-BC", "Thanksgiving Day", 2024, 10, 14)
_reg("CA", "CA-BC", "Remembrance Day", 2024, 11, 11)
_reg("CA", "CA-AB", "Family Day", 2024, 2, 19)
_reg("CA", "CA-AB", "Victoria Day", 2024, 5, 20)
_reg("CA", "CA-AB", "Thanksgiving Day", 2024, 10, 14)
_reg("CA", "CA-AB", "Remembrance Day", 2024, 11, 11)
_reg("CA", "CA-MB", "Louis Riel Day", 2024, 2, 19)
_reg("CA", "CA-MB", "Victoria Day", 2024, 5, 20)
_reg("CA", "CA-MB", "National Day for Truth and Reconciliation", 2024, 9, 30)
_reg("CA", "CA-MB", "Thanksgiving Day", 2024, 10, 14)
_reg("CA", "CA-NS", "Heritage Day", 2024, 2, 19)
_reg("CA", "CA-NS", "Remembrance Day", 2024, 11, 11)


@pytest.mark.parametrize("country,subdiv,name,year,month,day", [
    (c, s, n, y, m, d)
    for (c, s, n), ymds in list(HOLIDAY_GOLDS.items())
    if c in {"GB", "DE", "FR", "ES", "BR", "CA"}
    for (y, m, d) in ymds
])
def test_w1a_gold(country, subdiv, name, year, month, day):
    got = _dates_for(country, year, subdiv=subdiv)
    assert got[(name, subdiv)] == AstroDate(year, month, day)


# ==========================================================================
# Structural enforcement: every rule in every holiday_data/*.tab needs a gold.
# ==========================================================================
def _every_tab_rule_key():
    """(country, subdiv, name) for every rule row in every shipped .tab file."""
    keys = []
    for fn in sorted(os.listdir(_DATA_DIR)):
        if not fn.endswith(".tab"):
            continue
        cal = load_calendar(os.path.join(_DATA_DIR, fn))
        for rule in cal.rules:
            keys.append((cal.jurisdiction.upper(), rule.subdiv, rule.name))
    return keys


@pytest.mark.parametrize("country,subdiv,name", _every_tab_rule_key())
def test_every_tab_rule_has_a_gold(country, subdiv, name):
    """Enforces only for jurisdictions with a holiday_data/*.tab file present
    in THIS checkout -- countries whose data+golds haven't merged yet simply
    don't appear in ``_every_tab_rule_key()``, so parallel branches (adding
    e.g. de.tab) never conflict with each other here."""
    assert (country, subdiv, name) in HOLIDAY_GOLDS, (
        f"no gold registered for {country}/{subdiv}/{name!r}; "
        f"add one to HOLIDAY_GOLDS (see this module's docstring)")
