# -*- coding: utf-8 -*-
"""The az<->en semantic-parity block: each pair resolves to the SAME span."""

PARITY = [
    # rel_period / weekend / bare-weekday rollout
    ('gələn həftə', 'next week'),
    ('həftə sonu', 'this weekend'),
    ('cümə', 'friday'),
    ('sabah', 'tomorrow'),
    ('dünən', 'yesterday'),
    ('bugün', 'today'),
    ('o biri gün', 'day after tomorrow'),
    ('2 həftə sonra', 'in 2 weeks'),
    ('2 həftə əvvəl', '2 weeks ago'),
    ('3 gün sonra', 'in 3 days'),
    ('3 gün əvvəl', '3 days ago'),
    ('2 gün qabaq', '2 days ago'),
    ('5 il sonra', 'in 5 years'),
    ('10 il əvvəl', '10 years ago'),
    ('6 ay sonra', 'in 6 months'),
    ('2 saat sonra', 'in 2 hours'),
    ('15 dəqiqə sonra', 'in 15 minutes'),
    ('5 iyun 2027', 'june 5 2027'),
    ('20 iyul 1969', 'july 20 1969'),
    ('1 yanvar 2000', 'january 1 2000'),
    ('25 dekabr 2025', 'december 25 2025'),
    ('iyun 2027', 'june 2027'),
    ('yanvar 2020', 'january 2020'),
    ('1999', '1999'),
    ('2020', '2020'),
    ('15:30', '15:30'),
    ('gələn çərşənbə axşamı', 'next tuesday'),
    ('keçən cümə', 'last friday'),
    ('günorta', 'noon'),
    ('gecə yarısı', 'midnight'),
    ('44 eramızdan əvvəl', '44 bc'),
    ('1492 bizim eranın', '1492 ad'),
]
